#!/usr/bin/env python3
"""Transcribe the thirteenth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=21;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID;PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_BD24584C41DAE4DD","LIT_BD9F1C16BFFB2240","LIT_BEACD822B2E6860B","LIT_C604F0126CF213E1","LIT_C9AE5F305673D268")
def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Catalyst.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PROD","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale.",confidence="medium",value_status="review_assessment")
def build_phase(m,s):
 sid=m["source_id"];t=base(m,"Three repeatedly observed Fe phase-evolution groups under nominally identical in-situ CNT-CVD conditions.")
 for code,phase,out in (("GAMMA","gamma-rich metallic Fe","metallic Fe remains active; carbide not required"),("ALPHA","alpha-rich Fe","alpha-rich catalyst transforms more readily toward Fe3C during CNT growth"),("MIXED","mixed alpha/gamma/Fe3C","competing kinetic pathways yield mixed metallic/carbide active states")):
  rid=f"{sid}_{code}";r=run_row(sid,code,phase,out);r["data_type"]="experimental_repeated_run_group";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="nominal 8 nm Fe film on oxide support",active_metals="Fe",support_material="Al2O3 or SiO2 oxide support",metal_ratio_original="8 nm Fe",preparation_method="thin-film deposition",phase_or_state_summary=phase,activation_condition="Ar/H2 30/10 sccm at 750 C and ~150 mbar"));t["reactor_process_gas"].append(process_row(rid,1,"in_situ_XRD_CNT_CVD",reactor_type="in-situ XRD CVD chamber",temperature_setpoint_C="750",pressure_original="~150 mbar",pressure_kPa="15",carbon_source="C2H2",carbon_source_flow_original="1 sccm",carbon_source_flow_sccm="1",reducing_gas="H2",reducing_gas_flow_original="10 sccm",reducing_gas_flow_sccm="10",inert_gas="Ar",inert_gas_flow_original="30 sccm",inert_gas_flow_sccm="30",total_flow_original="41 sccm",total_flow_sccm="41"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT formation/catalyst phase",yield_original=out,yield_definition_original="In-situ XRD/ETEM phase observation; no mass yield",secondary_result_summary="Repeated phase groups had similar overall CNT yield and diameter distributions",CNT_type_reported="carbon nanotubes",CNT_type_confirmed="MWCNT-dominant",product_mixture_summary="CNTs including some bamboo structures and encapsulated catalyst",CNT_type_evidence="SEM/TEM/ETEM and in-situ XRD",morphology="CNT film with some bamboo-type structures",characterization_methods="in-situ XRD/XRR; SEM; HRTEM; ETEM"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="In-situ research-scale thin-film CVD coupon.",cost_driver_summary="Fe/oxide film, 750 C CVD and synchrotron/in-situ electron/X-ray characterization.",safety_risk="Acetylene/hydrogen at temperature and Fe/CNT nanoparticles.",emission_or_waste="CVD exhaust and Fe/CNT-coated substrates."));ev(t,s,sid,rid,"SPAN_0E57EBE824DEDBBFBA22","SPAN_252DD9390C921E3ED3D5","SPAN_0E57EBE824DEDBBFBA22")
 return t
def build_alloys(m,s):
 sid=m["source_id"];t=base(m,"All twelve unique pure/binary Fe-Co-Ni compositions represented in Table 1.")
 recs=(("FE","Fe","5.81","18.20","10.48","7.72","133"),("FE75CO25","Fe0.75Co0.25","7.10","25.06","10.14","14.92","210"),("FE50CO50","Fe0.50Co0.50","6.99","31.65","11.79","19.86","284"),("FE25CO75","Fe0.25Co0.75","5.61","25.29","10.41","14.88","265"),("CO","Co","3.77","23.27","10.52","12.75","338"),("FE75NI25","Fe0.75Ni0.25","5.12","20.01","10.05","9.96","195"),("FE50NI50","Fe0.50Ni0.50","4.07","19.55","10.15","9.40","231"),("FE25NI75","Fe0.25Ni0.75","2.58","15.17","8.75","6.42","249"),("NI","Ni","1.97","13.54","9.20","4.34","220"),("CO75NI25","Co0.75Ni0.25","2.39","19.14","11.29","7.85","328"),("CO50NI50","Co0.50Ni0.50","1.75","13.22","8.70","4.52","259"),("CO25NI75","Co0.25Ni0.75","2.00","15.67","8.93","6.74","338"))
 for code,comp,carbon,sr,so,delta,metric in recs:
  rid=f"{sid}_{code}";out=f"carbon content {carbon} wt%; product surface area {sr} m2/g; CNT-specific surface metric {metric}";t["source_run"].append(run_row(sid,code,comp,out));metals="; ".join(x for x in("Fe" if"FE"in code else "","Co" if"CO"in code else "","Ni" if"NI"in code else "")if x);t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"in-situ {comp} alloy nanoparticles",active_metals=metals,support_material="Mg-Al spinel oxide solid solution",metal_ratio_original=f"{comp}; total transition metal 6.7 wt%",precursor_summary="stoichiometric metal nitrates plus urea",preparation_method="combustion synthesis; attrition mill, sieve, ethanol wash, calcine 500 C 30 min",activation_condition="in-situ H2/CH4 reduction at 1070 C"));t["reactor_process_gas"].append(process_row(rid,1,"reduction_growth_one_step",reactor_type="fixed-bed high-temperature reactor",temperature_setpoint_C="1070",holding_time_min="6",carbon_source="CH4",reducing_gas="H2",total_flow_original="250 sccm H2/CH4 mixture",total_flow_sccm="250",gas_composition_summary="H2 with 18 mol% CH4"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="product carbon content",yield_original=f"{carbon} wt%",yield_value_standardized=carbon,yield_unit_standardized="wt.% carbon in reacted product",yield_definition_original="flash-combustion carbon content",secondary_result_summary=out,CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT-rich",product_mixture_summary="SWCNT web plus residual alloy/spinel",CNT_type_evidence="TEM/Raman and BET surface-area difference",BET_surface_area_product_m2_g=sr,characterization_methods="TEM; Raman; flash combustion; BET surface area"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Six-minute laboratory oxide-powder reduction/growth run.",cost_driver_summary="Combustion-made spinel, 1070 C furnace and H2/CH4.",safety_risk="Hydrogen/methane at 1070 C and Fe/Co/Ni nanopowders.",emission_or_waste="Hot reducing-gas exhaust and metal/spinel-containing CNT product."));ev(t,s,sid,rid,"SPAN_116095367105C16F326C","SPAN_08B551DA64B37FEC066B","SPAN_116095367105C16F326C")
 return t
def build_weaklinks(m,s):
 sid=m["source_id"];t=base(m,"Two device-contact variants using the same aerosol FC-CVD SWCNT synthesis and thermophoretic dry deposition.")
 for code,contact,temp,time,out in (("MORE","80 nm MoRe","900","5","transparent superconducting contact; measured supercurrent above 50 nA"),("MORE_PD","80 nm MoRe + 5 nm Pd","220","10","transparent contact after low-temperature anneal")):
  rid=f"{sid}_{code}";r=run_row(sid,code,contact,out);r["data_type"]="experimental_post_processing";r["target_track"]="SWCNT_superconducting_device";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="ferrocene floating catalyst; deposited SWCNT on "+contact,active_metals="Fe",support_material="suspended gap between prepatterned "+contact+" electrodes",precursor_summary="ferrocene carried by CO; CO2 diameter-control coflow",preparation_method="aerosol FC-CVD followed by thermophoretic dry deposition",phase_or_state_summary="mean SWCNT diameter 1.8 ± 0.3 nm"));t["reactor_process_gas"].append(process_row(rid,1,"aerosol_FC_CVD_and_device_anneal",reactor_type="FC-CVD plus thermophoretic precipitator and vacuum rapid-thermal annealer",temperature_setpoint_C=f"growth recipe referenced; device anneal {temp}",holding_time_min=time,carbon_source="CO",cofeed_or_reactive_gas="CO2 diameter-control flow",inert_gas="Ar/H2 3% H2 during device anneal",pressure_original="anneal residual pressure ~3e-4 mbar",process_note=f"Ferrocene/CO FC-CVD; aerosol concentration ~1e5 cm-3; thermophoretic deposition between 100 C top and water-cooled bottom plates; anneal {temp} C."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="suspended weak-link device outcome",yield_original=out,yield_definition_original="Electrical/contact outcome; no CNT mass yield",secondary_result_summary=out,CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary="individual suspended aerosol SWCNT on superconducting electrodes",CNT_type_evidence="UV-vis-NIR diameter plus SEM/electrical transport",outer_diameter_mean_nm="1.8",outer_diameter_range_nm="mean 1.8 ± 0.3",characterization_methods="SMPS; UV-vis-NIR; SEM; low-temperature electrical transport",application_property_summary=out));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="119 electrode pairs per 5 x 5 mm chip; few suspended tubes per chip.",cost_driver_summary="MoRe/Pd microfabrication, FC-CVD aerosol, thermophoresis, high vacuum and cryogenic test.",safety_risk="CO/CO2/ferrocene aerosol, high-temperature anneal and nanomaterial exposure.",emission_or_waste="Metal/fluorocarbon lithography waste and FC-CVD exhaust."));ev(t,s,sid,rid,"SPAN_018B9C358D005939DEC6","SPAN_1F3786E4D70DE87749FF","SPAN_1F3786E4D70DE87749FF")
 return t
def build_pillars(m,s):
 sid=m["source_id"];t=base(m,"Six patterned pillar diameters, each grown by the common LPCVD recipe and compared before/after 20 nm NbTiN ALD coating.")
 for d in (30,50,60,80,100,150):
  rid=f"{sid}_D{d}";out=f"120 ± 5 micrometre VA-MWCNT pillar, {d} micrometre diameter; pristine/coated compression comparison";r=run_row(sid,f"D{d}",f"{d} micrometre NbTiN-coated pillar",out);r["data_type"]="experimental_post_processing";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="5 nm Fe on Ti/TiN patterned pillar",active_metals="Fe",support_material="10/50 nm Ti/TiN over 500 nm SiO2/Si",metal_ratio_original="5 nm Fe",preparation_method="optical lithography, e-beam evaporation and lift-off",preparation_detail=f"circular catalyst pattern for {d} micrometre pillar"));t["reactor_process_gas"].append(process_row(rid,1,"LPCVD_then_NbTiN_ALD",reactor_type="Aixtron Black Magic Pro plus plasma ALD",temperature_setpoint_C="650 CNT growth; ALD precursor temperatures 100/75",holding_time_min="10 CNT growth; 122 ALD cycles",pressure_original="80 mbar CNT growth",pressure_kPa="8",carbon_source="C2H2",carbon_source_flow_original="50 sccm",carbon_source_flow_sccm="50",reducing_gas="H2",reducing_gas_flow_original="700 sccm",reducing_gas_flow_sccm="700",cofeed_or_reactive_gas="TBTDEN/TDMAT with N2 plasma and H2; 300 W",process_note="20 nm NbTiN conformal coat; ~0.5 A/min; N2 5 sccm Ti cycles, additional H2 80 sccm Nb cycles."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="pillar morphology/compression",yield_original=out,yield_definition_original="Geometry and nanoindentation outcome; no mass yield",secondary_result_summary="Smaller pristine pillars show higher elastic modulus; 20 nm coating brittle-fails and penetrates mainly at exterior for larger pillars",CNT_type_reported="vertically aligned multi-walled carbon nanotube pillar",CNT_type_confirmed="VA-MWCNT",product_mixture_summary="NbTiN-coated VA-MWCNT pillar",CNT_type_evidence="SEM and Raman",length_summary="120 ± 5 micrometres",morphology=f"cylindrical {d} micrometre pillar",alignment_or_array="vertically aligned pillar",characterization_methods="SEM; Raman; nanoindentation/compression",application_property_summary="foam-like energy absorption; coated/pristine comparison"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Micropatterned wafer pillar.",cost_driver_summary="Ti/TiN/Fe deposition, lithography, LPCVD and 122-cycle plasma ALD.",safety_risk="Hydrogen/acetylene, organometallic ALD precursors and plasma.",emission_or_waste="CVD/ALD exhaust and patterned wafer waste."));ev(t,s,sid,rid,"SPAN_39E871FCAD0711201567","SPAN_39E871FCAD0711201567","SPAN_39E871FCAD0711201567")
 return t
def build_preheat(m,s):
 sid=m["source_id"];t=base(m,"Twelve methane-flow points at 950/850 C plus the two lower-temperature reported points.")
 rows=[]
 for temp,counts in ((950,(3,1,10,6,2,0)),(850,(1,2,4,8,3,1))):
  for flow,count in zip((1000,750,500,250,125,62),counts):rows.append((f"T{temp}_M{flow}",temp,flow,str(count),"mean diameter 3.2 nm" if temp==950 else "mean diameter 3.8 nm"))
 rows.extend((("T750_M250",750,250,"few","diameter 0.85-3.3 nm; length 1-5 micrometres"),("T700_M125",700,125,"fewer than at 750 C","diameter 0.9-2.2 nm; length 2-5 micrometres")))
 for code,temp,flow,count,out in rows:
  rid=f"{sid}_{code}";res=f"{count} CNTs per 100 micrometre2; {out}";t["source_run"].append(run_row(sid,code,f"growth {temp} C, CH4 {flow} sccm",res));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="ferritin nanoparticles on Si",active_metals="Fe",support_material="silicon substrate",precursor_summary="0.5 g/L ferritin solution",preparation_method="ferritin solution deposition",catalyst_particle_size_mean_nm="~12",catalyst_particle_size_qualifier="AFM ferritin diameter"));t["reactor_process_gas"].append(process_row(rid,1,"three_zone_preheated_carbon_CVD",reactor_type="1-inch quartz tube, three independently controlled heating zones",temperature_setpoint_C=str(temp),carbon_source="CH4; C2H4",carbon_source_flow_original=f"CH4 {flow} sccm; C2H4 20 sccm",carbon_source_flow_sccm=str(flow),reducing_gas="H2",reducing_gas_flow_original="500 sccm",reducing_gas_flow_sccm="500",total_flow_original=f"{520+flow} sccm",total_flow_sccm=str(520+flow),process_note="Carbon source passes higher-temperature preheat/transition zones before the lower-temperature growth zone."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT count/productivity",yield_original=f"{count} CNTs per 100 micrometre2",yield_definition_original="AFM count over twenty 10 x 10 micrometre areas; productivity additionally defined as total CNT length per area",secondary_result_summary=res,CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary=res,CNT_type_evidence="AFM/Raman",outer_diameter_mean_nm="3.2" if temp==950 else "3.8" if temp==850 else "not_reported",outer_diameter_range_nm="0.85-3.3" if temp==750 else "0.9-2.2" if temp==700 else "not_reported",length_summary="1-5 micrometres" if temp==750 else "2-5 micrometres" if temp==700 else "not_reported",characterization_methods="AFM; Raman"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Silicon-coupon three-zone CVD screening point.",cost_driver_summary="Ferritin, three-zone furnace, high H2/CH4 flow and AFM mapping.",safety_risk="Hydrogen/methane/ethylene at 700-950 C.",emission_or_waste="Hydrocarbon exhaust and ferritin/CNT-coated Si."));ev(t,s,sid,rid,"SPAN_0D25C28E5120FDD2BEFE","SPAN_4BDD838D6E676A105708","SPAN_0D25C28E5120FDD2BEFE")
 return t
BUILDERS:dict[str,Callable]={"LIT_BD24584C41DAE4DD":build_phase,"LIT_BD9F1C16BFFB2240":build_alloys,"LIT_BEACD822B2E6860B":build_weaklinks,"LIT_C604F0126CF213E1":build_pillars,"LIT_C9AE5F305673D268":build_preheat}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"]for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_021_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
