#!/usr/bin/env python3
"""Transcribe the fourteenth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,issue_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=22;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID;PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_CA678F825E54BE45","LIT_D1AF7614B5E2F098","LIT_D1DCD57210281936","LIT_D5BD8BD50A4E57A2","LIT_D69AB1AB29D0F242")
def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Catalyst.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PROD","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale.",confidence="medium",value_status="review_assessment")
def build_plasma(m,s):
 sid=m["source_id"];t=base(m,"One experimentally demonstrated continuous microwave-plasma MWCNT deposition process on moving stainless-steel strip.");rid=f"{sid}_CONT";t["source_run"].append(run_row(sid,"CONT","continuous microwave-plasma CNT strip","Successful continuous Fe-encapsulating MWCNT growth confirmed by TEM/TGA/EDX"));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="ferrocene/xylene coating on stainless-steel strip",active_metals="Fe",support_material="1.4310 stainless steel strip, 0.005-0.05 mm thick",precursor_summary="ferrocene dissolved in xylene",preparation_method="dip coating/painted catalyst layer",phase_or_state_summary="Fe encapsulated in MWCNT product"));t["reactor_process_gas"].append(process_row(rid,1,"continuous_microwave_thermal_plasma_CVD",reactor_type="atmospheric microwave plasma jet with moving strip cassettes",temperature_setpoint_C="1000-1300 K",pressure_original="atmospheric",pressure_kPa="101.325",carbon_source="C2H4",carbon_source_flow_original="1000 sccm common recipe",carbon_source_flow_sccm="1000",reducing_gas="H2",reducing_gas_flow_original="3000 sccm common recipe",reducing_gas_flow_sccm="3000",inert_gas="Ar/N2 plasma gases",total_flow_original="at least 4000 sccm plus plasma gases",process_note="Microwave power up to 800 W; strip speed 0.01-0.1 m/h; chamber air-plasma purge 30 min."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="continuous MWCNT deposition",yield_original="MWCNT growth and Fe encapsulation confirmed across replicate samples",yield_definition_original="TEM/TGA/EDX confirmation; no mass yield",secondary_result_summary="Average EDX values based on 10 samples under common conditions",CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary="Fe-containing MWCNT coating on steel strip",CNT_type_evidence="TEM and MWCNT-characteristic TGA oxidation",morphology="CNT coating on continuous conductive strip",characterization_methods="SEM/EDX; TEM; TGA"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Continuous moving metal strip at 0.01-0.1 m/h.",cost_driver_summary="800 W microwave plasma, 1000-1300 K strip, very high H2/ethylene/plasma-gas flow and catalyst coating.",safety_risk="Hydrogen/ethylene plasma, hot moving metal and ferrocene/xylene.",emission_or_waste="Plasma/CVD exhaust and solvent/catalyst coating waste."));ev(t,s,sid,rid,"SPAN_31E83331E84CFC896495","SPAN_4081542C7BC6EF2F9196","SPAN_31E83331E84CFC896495");return t
def build_joint(m,s):
 sid=m["source_id"];t=base(m,"Three source-described aerosol-CVD campaigns: catalyst-feed, ethylene and toluene/ethylene response surfaces.")
 recs=(("FERROCENE","ferrocene-feed campaign","ferrocene solution concentration/feed varied","yield rises with catalyst feed but excess leaves unused particles and changes diameter"),("ETHYLENE","ethylene concentration campaign","ethylene varied at fixed toluene 0.15 vol% and ferrocene feed 65 microgram/min","yield peaks near 0.4 vol% ethylene; diameter tunable 1.3-2.2 nm; nucleation/activation enhanced"),("GRID","ethylene-toluene joint optimization","joint feedstock grid","best reported TCF: 57 ohm/sq at 90% T550 with synthesis yield 0.24 cm2/L"))
 for code,label,var,out in recs:
  rid=f"{sid}_{code}";r=run_row(sid,code,label,out);r["data_type"]="experimental_optimization_summary";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="ferrocene/thiophene floating catalyst",active_metals="Fe",support_material="floating/no solid support",precursor_summary="ferrocene and thiophene dissolved in toluene",preparation_method="solution-fed aerosol FC-CVD",preparation_detail=var));t["reactor_process_gas"].append(process_row(rid,1,"aerosol_FC_CVD_optimization",reactor_type="vertical 16 mm ID, 1.3 m quartz reactor",temperature_setpoint_C="1000",carbon_source="ethylene and toluene",reducing_gas="H2 carrier",cofeed_or_reactive_gas="ferrocene/thiophene/toluene solution",process_note=var+"; isothermal zone 40 cm (±10 C)."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="90%-transmittance film area per gas volume",yield_original=out,yield_definition_original="Rate of collection of film at 90% transmittance normalized by total gas flow",secondary_result_summary=out,CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary="SWCNT aerosol film",CNT_type_evidence="UV-vis-NIR, FTIR, TEM and Raman",outer_diameter_range_nm="1.3-2.2 across ethylene campaign" if code=="ETHYLENE" else "not_reported",characterization_methods="UV-vis-NIR; FTIR; Raman; TEM; four-point sheet resistance",application_property_summary=out));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Continuous aerosol film collection; yield normalized in cm2/L.",cost_driver_summary="1000 C vertical furnace, H2, ethylene/toluene and ferrocene/thiophene feed.",safety_risk="Hydrogen, ethylene, toluene, thiophene and ferrocene aerosol.",emission_or_waste="Hydrocarbon/organometallic exhaust and filter film waste."));ev(t,s,sid,rid,"SPAN_1F66A941AB83C368B383","SPAN_1F66A941AB83C368B383","SPAN_2332958144E14E67E2B9")
  t["review_issue_log"].append(issue_row(f"{rid}_ISSUE",sid,rid,"series_aggregation","reactor_process_gas",f"{rid}_S01","process_note","Campaign is represented as a source-level response summary because most individual grid coordinates are figure-only.",f"EVD_{rid}_PROC","medium"))
 return t
def build_plasma_orientation(m,s):
 sid=m["source_id"];t=base(m,"Matched no-plasma and 10 min oxygen-plasma Fe-catalyst conditions under the same thermal CVD recipe.")
 for code,plasma,out in (("RAW","none","horizontal MWCNT network"),("O2P10","oxygen plasma 10 min","ultradense vertically aligned MWCNT carpet with lower diameter/better quality")):
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,f"Fe catalyst, {plasma}",out));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="2 nm Fe on substrate",active_metals="Fe",support_material="cleaned substrate",metal_ratio_original="2 nm Fe",preparation_method="Fe sputtering followed by "+plasma,preparation_detail="oxygen plasma increases roughness and produces more uniform, smaller catalyst islands" if code!="RAW" else "as-sputtered film"));t["reactor_process_gas"].append(process_row(rid,1,"thermal_CVD",reactor_type="thermal CVD chamber",temperature_setpoint_C="800",carbon_source="C2H2",carbon_source_flow_original="20 sccm",carbon_source_flow_sccm="20",inert_gas="Ar",inert_gas_flow_original="60 sccm",inert_gas_flow_sccm="60",total_flow_original="80 sccm",total_flow_sccm="80",process_note="Ar heat-up; introduce acetylene at 800 C; cool under Ar."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT orientation/density",yield_original=out,yield_definition_original="SEM/TEM/Raman morphology; no mass yield",secondary_result_summary=out,CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary=out,CNT_type_evidence="HRTEM and Raman",morphology=out,alignment_or_array="vertical carpet" if code!="RAW" else "horizontal network",characterization_methods="FESEM; AFM; HRTEM; Raman"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Substrate-coupon comparative CVD.",cost_driver_summary="Fe sputtering, optional 10 min oxygen plasma and 800 C acetylene/argon CVD.",safety_risk="Oxygen plasma, acetylene at 800 C and CNT exposure.",emission_or_waste="CVD exhaust and Fe/CNT-coated substrates."));ev(t,s,sid,rid,"SPAN_1F8994D55DC84D691260","SPAN_1F8994D55DC84D691260","SPAN_B51587F0B5CA3A6EAB39")
 return t
def build_odako(m,s):
 sid=m["source_id"];t=base(m,"One odako SWCNT growth process applied across carbon surfaces, with catalyst/support inversion explicit.");rid=f"{sid}_ODAKO";t["source_run"].append(run_row(sid,"ODAKO","1 nm Fe capped by 5 nm Al2O3 on carbon surface","dense SWCNT arrays attached to carbon surfaces through alumina flakes"));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="1 nm Fe under 5 nm Al2O3 overlayer",active_metals="Fe",support_material="carbon film/fiber/fabric surface; Al2O3 flakes above Fe",metal_ratio_original="Fe 1 nm / Al2O3 5 nm",preparation_method="line-of-sight evaporation of Fe followed immediately by Al2O3",phase_or_state_summary="catalyst on underside of lifted alumina flakes; hybrid tip/base odako growth"));t["reactor_process_gas"].append(process_row(rid,1,"water_assisted_low_pressure_CVD",reactor_type="low-pressure CVD",temperature_setpoint_C="750",carbon_source="C2H4",carbon_source_flow_original="2 sccm",carbon_source_flow_sccm="2",reducing_gas="atomic hydrogen",cofeed_or_reactive_gas="H2O 2 sccm",process_note="Atomic-hydrogen flow value is source-extraction-ambiguous; exact value not transcribed."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="dense attached SWCNT array",yield_original="odako dense SWCNT arrays on multiple carbon surfaces",yield_definition_original="SEM/TEM/XPS morphology; no mass yield",secondary_result_summary="SWCNTs remain attached via alumina flakes supporting thousands of catalyst particles",CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary="dense fibril/array on carbon film, fiber and fabric",CNT_type_evidence="SEM/TEM and spectroscopy",morphology="dense arrays emanating from supported catalyst flakes",alignment_or_array="dense array",characterization_methods="SEM; TEM; XPS"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Demonstrated on carbon film, individual fibers and woven carbon material.",cost_driver_summary="Ultrathin Fe/Al2O3 evaporation, atomic-hydrogen source and 750 C low-pressure CVD.",safety_risk="Hydrogen radicals, ethylene/water at high temperature and CNT-coated fibers.",emission_or_waste="CVD exhaust and coated carbon substrates."));ev(t,s,sid,rid,"SPAN_2836B776A2E4D2182987","SPAN_349C9147C2A3A2D63E53","SPAN_2836B776A2E4D2182987");return t
def build_buffers(m,s):
 sid=m["source_id"];t=base(m,"Four oxide-buffer comparisons at 600 C plus two temperature-response summaries for ALD and e-beam Al2O3.")
 buffers=(("ALD","ALD Al2O3","dense VACNT; smaller/more numerous catalyst particles"),("EB","e-beam Al2O3","thickest VACNT; roughest buffer and longest catalyst lifetime"),("SPUT","sputtered Al2O3","almost no VACNT due to serious Ostwald ripening"),("SIO2","SiO2","very sparse VACNT"))
 for code,buf,out in buffers:
  rid=f"{sid}_{code}_600";t["source_run"].append(run_row(sid,f"{code}_600",f"{buf}, 600 C",out));t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"1 nm Fe on 20 nm {buf}",active_metals="Fe",support_material=f"20 nm {buf} on substrate",metal_ratio_original="Fe 1 nm / oxide 20 nm",preparation_method="Fe electron-beam evaporation over prepared oxide buffer",activation_condition="H2 700 sccm, 550 C, 3 min"));t["reactor_process_gas"].append(process_row(rid,1,"VACNT_CVD",reactor_type="Aixtron Black Magic II",temperature_setpoint_C="600",holding_time_min="30",carbon_source="C2H2",carbon_source_flow_original="100 sccm",carbon_source_flow_sccm="100",reducing_gas="H2",reducing_gas_flow_original="700 sccm",reducing_gas_flow_sccm="700",total_flow_original="800 sccm",total_flow_sccm="800"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="VACNT growth/morphology",yield_original=out,yield_definition_original="Cross-sectional SEM growth outcome; no mass yield",secondary_result_summary=out,CNT_type_reported="vertically aligned carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary=out,CNT_type_evidence="TEM/Raman/SEM",morphology="vertically aligned array" if "almost no" not in out and "sparse" not in out else out,alignment_or_array="VACNT",characterization_methods="SEM; TEM; Raman; AFM; XPS; XRR"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Oxide-buffer wafer coupon.",cost_driver_summary="20 nm oxide deposition route, 1 nm Fe evaporation, 600 C CVD and high H2 flow.",safety_risk="Hydrogen/acetylene at temperature and CNT/Fe nanoparticle handling.",emission_or_waste="CVD exhaust and oxide/Fe/CNT-coated wafers."));ev(t,s,sid,rid,"SPAN_4244116424B84DE6D13A","SPAN_4244116424B84DE6D13A","SPAN_0C1CD46F50D84C74DEFD")
 for code,buf in (("ALD_SERIES","ALD Al2O3"),("EB_SERIES","e-beam Al2O3")):
  rid=f"{sid}_{code}";r=run_row(sid,code,f"{buf} 500-650 C series","growth rate rises below 600 C and falls above 600 C due to Ostwald ripening","medium");r["data_type"]="experimental_series_summary";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"1 nm Fe on 20 nm {buf}",active_metals="Fe",support_material=buf,preparation_method="thin-film oxide plus Fe evaporation"));t["reactor_process_gas"].append(process_row(rid,1,"VACNT_temperature_series",reactor_type="Aixtron Black Magic II",temperature_setpoint_C="500-650",holding_time_min="30",carbon_source="C2H2 100 sccm",reducing_gas="H2 700 sccm",process_note="Discrete plotted temperatures aggregated because exact growth-rate coordinates are figure-derived."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="growth-rate temperature response",yield_original="maximum near 600 C; decline above 600 C",yield_definition_original="Figure 7 trend; exact coordinates not transcribed",secondary_result_summary="High-temperature decline attributed to catalyst Ostwald ripening and lifetime loss",CNT_type_reported="VACNT",CNT_type_confirmed="MWCNT",product_mixture_summary="VACNT series",CNT_type_evidence="SEM/TEM/Raman",alignment_or_array="vertical arrays",characterization_methods="cross-sectional SEM; TEM; Raman"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Multi-temperature wafer-coupon series.",cost_driver_summary="Repeated CVD runs, oxide/Fe films and high H2 use.",safety_risk="Hydrogen/acetylene at 500-650 C.",emission_or_waste="CVD exhaust and multiple coated wafers."));ev(t,s,sid,rid,"SPAN_4244116424B84DE6D13A","SPAN_4244116424B84DE6D13A","SPAN_0C1CD46F50D84C74DEFD");t["review_issue_log"].append(issue_row(f"{rid}_ISSUE",sid,rid,"plot_series","yield_quality",f"{rid}_PROD","yield_original","Exact growth-rate coordinates remain figure-only; only the author-stated trend is stored.",f"EVD_{rid}_PROD","medium"))
 return t
BUILDERS:dict[str,Callable]={"LIT_CA678F825E54BE45":build_plasma,"LIT_D1AF7614B5E2F098":build_joint,"LIT_D1DCD57210281936":build_plasma_orientation,"LIT_D5BD8BD50A4E57A2":build_odako,"LIT_D69AB1AB29D0F242":build_buffers}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"]for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_022_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
