#!/usr/bin/env python3
"""Transcribe the ninth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Any, Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,issue_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=17;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_7DB638A390C20E74","LIT_85779E66B8B0D55E","LIT_87B8240D8CDFE77C","LIT_9181CCCE7A19C985","LIT_91BE111AC6247FA8")
def base(m,scope):
    t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Catalyst/material.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PRODUCT","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale context.",confidence="medium",value_status="review_assessment")
def build_retina(m,s):
 sid=m["source_id"];t=base(m,"Four uniform and two patterned VACNT preparations separated by Al underlayer, oxygen-plasma treatment and pattern/growth time.")
 recs=(("FE","Fe only",False,False,"5","uniform 30-38 micrometre forest; prone to cracking/delamination"),("ALFE","Al/Fe",True,False,"5","uniform 30-38 micrometre forest; mechanically stable; best neurite outgrowth"),("FE_PL","Fe only + oxygen plasma",False,True,"5","uniform 30-38 micrometre plasma-functionalized forest; cracking/delamination"),("ALFE_PL","Al/Fe + oxygen plasma",True,True,"5","stable uniform forest but plasma reduced neurite outgrowth versus untreated Al/Fe"),("ALFE_PAT100","Al/Fe patterned 100 micrometre rows",True,False,"3","21-31 micrometre tall rows; supported retinal neurite growth through 7 DIV"),("ALFE_PAT2P5","Al/Fe high-aspect pattern",True,False,"3","2.5 micrometre row width, 10 micrometre spacing and 20 micrometre height"))
 for code,label,al,pl,mins,out in recs:
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,label,out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=("4-8 nm Al / " if al else "")+"6-12 nm Fe on 300 nm SiO2/Si",active_metals="Fe",support_material=("Al underlayer on " if al else "")+"300 nm thermal SiO2/Si",metal_ratio_original="Al 4-8 nm; Fe 6-12 nm" if al else "Fe 6-12 nm",preparation_method="thermal evaporation over full chip" if "PAT" not in code else "photolithographic patterning and thermal evaporation",post_preparation_condition="O2 plasma 300 mTorr, 5 min, 50 W" if pl else "no plasma"))
  t["reactor_process_gas"].append(process_row(rid,1,"atmospheric_CVD",reactor_type="2-inch quartz tube",temperature_setpoint_C="650",holding_time_min=mins,carbon_source="C2H4",carbon_source_flow_original="200 sccm",carbon_source_flow_sccm="200",reducing_gas="H2",reducing_gas_flow_original="100 sccm",reducing_gas_flow_sccm="100",inert_gas="Ar",inert_gas_flow_original="600 sccm",inert_gas_flow_sccm="600",total_flow_original="900 sccm",total_flow_sccm="900",gas_composition_summary="C2H4/H2 2:1 plus Ar"))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="VACNT morphology/mechanical integrity",yield_original=out,yield_definition_original="SEM/TEM and retinal-culture outcome; no mass yield.",secondary_result_summary=out,CNT_type_reported="vertically aligned carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary="VACNT forest",CNT_type_evidence="TEM shows multi-walled CNT; SEM/Raman/XPS",length_summary="30-38 micrometres" if mins=="5" else "21-31 micrometres" if code=="ALFE_PAT100" else "20 micrometres",morphology="dense vertical forest",alignment_or_array="vertically aligned forest",characterization_methods="SEM; TEM; Raman 532 nm; XPS; contact angle; retinal-cell culture"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Approximately 1 cm2 chip or 6 x 6 mm patterned area.",cost_driver_summary="Metal evaporation, lithography where applicable, 650 C CVD and optional oxygen plasma.",safety_risk="Hydrogen/ethylene at high temperature; CNT detachment and plasma exposure.",emission_or_waste="CVD exhaust and metal/CNT-coated chips."));ev(t,s,sid,rid,"SPAN_4AA8624DE3F71601EA37","SPAN_4AA8624DE3F71601EA37","SPAN_A9BFF3160B14B42E136B")
 return t
def build_sensor(m,s):
 sid=m["source_id"];t=base(m,"Three sequential author-generated CNT post-processing/electrode records; purchased MWCNT synthesis is not reconstructed.")
 recs=(("GO_MWNT","GO-MWNT hybrid","0.5 mg/mL acid-carboxylated MWCNT + 1.0 mg/mL GO; 2:1 GO:MWNT; ultrasonicate 2 h, centrifuge 8000 then 14000 rpm; vacuum dry 50 C 12 h","stable GO-MWNT hybrid"),("GO_MWNT_LCYS","L-cysteine-functionalized GO-MWNT","10 mg hybrid in 5 M HCl/0.1 M L-cysteine at 4:1 hybrid:L-cys; sonicate 1 h, stir 80 C 1 h, centrifuge/wash; vacuum dry 80 C 12 h","hydrophilic GO-MWNT-L-cys nanocomposite"),("ERGO_ELECTRODE","electrochemically reduced GO-MWNT-L-cys/GCE","0.2 mg/mL colloid sonicated 1.5 h; 6 microlitre drop-cast on polished GCE; vacuum/N2 dry then electrochemical reduction","Pb2+ sensor with enhanced selectivity; LOD 0.58 nM"))
 for code,label,proc,out in recs:
  rid=f"{sid}_{code}";r=run_row(sid,code,label,out);r["data_type"]="experimental_post_processing";r["target_track"]="CNT_sensor_material";t["source_run"].append(r)
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=label,active_metals="not_applicable",support_material="graphene oxide" if code!="ERGO_ELECTRODE" else "glassy carbon electrode",precursor_summary="purchased >95 wt.% MWCNT, 20-30 nm OD, 0.5-2 micrometre length; GO; L-cysteine",preparation_method="solution hybridization/functionalization/electrode modification",preparation_detail=proc,phase_or_state_summary=label))
  t["reactor_process_gas"].append(process_row(rid,1,"CNT_functionalization_or_electrode",reactor_type="aqueous sonication/centrifugation" if code!="ERGO_ELECTRODE" else "drop casting and three-electrode electrochemical cell",temperature_setpoint_C="room/50 dry" if code=="GO_MWNT" else "80" if code=="GO_MWNT_LCYS" else "room",holding_time_min="120 plus separation/drying" if code=="GO_MWNT" else "60 sonication + 60 stirring + 720 drying" if code=="GO_MWNT_LCYS" else "90 sonication plus drying/electroreduction",carbon_source="pre-existing MWCNT and graphene oxide",process_note=proc))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="nanocomposite/electrode formation",yield_original=out,yield_definition_original="Material/sensor outcome; no CNT production yield.",secondary_result_summary=out,CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT input material",product_mixture_summary=label,CNT_type_evidence="supplier specification plus Raman/AFM/ATR-IR",outer_diameter_range_nm="20-30",length_summary="0.5-2 micrometres",characterization_methods="ATR-IR; UV-vis; Raman; AFM; CV; EIS; stripping voltammetry",application_property_summary=out))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Milligram/millilitre laboratory sensor-material preparation.",cost_driver_summary="Purchased MWCNT/GO/L-cysteine, long sonication, high-speed centrifugation and electrode preparation.",safety_risk="Concentrated HNO3/H2SO4/HCl and nanomaterial handling.",emission_or_waste="Acidic wash/centrifuge liquids and carbon nanomaterial residue."));ev(t,s,sid,rid,"SPAN_3DFA7A2348F950A72D7A","SPAN_3E91C461983A542A164E","SPAN_15D59B7D417C9E50A48A")
 t["review_issue_log"].append(issue_row(f"{sid}_ISSUE_GROWTH",sid,f"{sid}_GO_MWNT","source_scope","source_run",f"{sid}_GO_MWNT","data_type","MWCNTs were purchased; all rows are source-specific post-processing/sensor fabrication, not CNT growth.",f"EVD_{sid}_GO_MWNT_CAT","high"));return t
def build_feedstocks(m,s):
 sid=m["source_id"];t=base(m,"Nine individually named hydrocarbon feedstock optimization campaigns using a common Al2O3/Fe water-assisted CVD system.")
 feeds=(("TDN","trans-decahydronaphthalene","saturated ring"),("CH4","methane","saturated chain"),("C3H8","propane","saturated chain"),("C4H10","butane","saturated chain"),("NHEX","n-hexane","saturated chain"),("DCPD","dicyclopentadiene","unsaturated ring"),("BUTADIENE","1,3-butadiene","unsaturated chain"),("C2H4","ethylene","unsaturated chain"),("C2H2","acetylene","unsaturated chain"))
 for code,feed,cls in feeds:
  rid=f"{sid}_{code}";out="no SWCNT forest under optimized survey" if code=="CH4" else "SWCNT forest height >100 micrometres after sequential optimization";r=run_row(sid,code,f"{feed} water-assisted CVD campaign",out,"medium");r["data_type"]="experimental_optimization_summary";t["source_run"].append(r)
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label="1.5 nm Fe / 40 nm Al2O3",active_metals="Fe",support_material="40 nm sputtered Al2O3",metal_ratio_original="Al2O3 40 nm / Fe 1.5 nm",preparation_method="sequential sputtering",activation_condition="He/H2 1:9 at 750 C"))
  t["reactor_process_gas"].append(process_row(rid,1,"water_assisted_CVD_optimization",reactor_type="fully automated CVD system with exchange chamber",temperature_setpoint_C="725-900 optimized",holding_time_min="10",carbon_source=feed,carbon_source_flow_original="feed-specific optimized; <100 sccm typical and lowered for highly reactive feeds",inert_gas="He",total_flow_original="1 L/min",total_flow_sccm="1000",cofeed_or_reactive_gas="water 50-500 ppm optimized",gas_composition_summary=f"{feed} ({cls}) + water enhancer in He"))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="SWCNT forest formation/height",yield_original=out,yield_definition_original="Optimized forest height; exact feed/temperature/water optimum is figure/table-specific and not reproduced in parsed text.",secondary_result_summary="Average diameter across successful feeds 2.5-3.1 nm; density 0.028-0.046 g/cm3; acetylene highest reactivity/lowest required input.",CNT_type_reported="single-wall carbon nanotube forest",CNT_type_confirmed="SWCNT forest" if code!="CH4" else "not_applicable",product_mixture_summary=out,CNT_type_evidence="SEM/TEM/FTIR/Raman",outer_diameter_range_nm="average 2.5-3.1; distributions ~1 to >4",morphology="vertical forest" if code!="CH4" else "no forest",alignment_or_array="vertically aligned forest",characterization_methods="SEM; TEM; FTIR; Raman; gravimetric density"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Optimization campaign within ~2000 automated CVD syntheses across all feeds.",cost_driver_summary="Automated 725-900 C CVD, sputtered catalyst, hydrocarbon feed, helium/hydrogen and water control.",safety_risk="Flammable/reactive hydrocarbons and hydrogen at high temperature.",emission_or_waste="Hydrocarbon CVD exhaust, soot/tar under excessive feed and catalyst-coated substrates."));ev(t,s,sid,rid,"SPAN_4C8E34641459F89474D0","SPAN_0AA8EE9FE744693B6657","SPAN_00220B5FC56ECC6374D8")
  t["review_issue_log"].append(issue_row(f"{rid}_ISSUE_OPT",sid,rid,"series_aggregation","reactor_process_gas",f"{rid}_S01","temperature_setpoint_C","Each feed underwent sequential optimization; exact optimum coordinates are not exposed in the parsed text, so only stated ranges/outcomes are retained.",f"EVD_{rid}_PROC","medium"))
 return t
def build_filled(m,s):
 sid=m["source_id"];t=base(m,"Two source-described filled-CNT CVD syntheses; externally supplied fluidized-bed MWCNTs are not represented as an author growth run.")
 for code,label,metals,solvent,out,ratio in (("FECO","FeCo-filled CNT","Fe; Co","trichlorobenzene with ferrocene+cobaltocene","Fe-Co alloy-filled CNT; ID/IG 0.84","0.84"),("FE","Fe-filled CNT","Fe","dichlorobenzene with ferrocene","Fe-filled CNT; ID/IG 0.51","0.51")):
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,label,out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=label+" floating precursor",active_metals=metals,support_material="floating/no solid support",precursor_summary=("ferrocene and cobaltocene" if code=="FECO" else "ferrocene")+f" dissolved in {solvent}",preparation_method="liquid injection floating-catalyst CVD"))
  t["reactor_process_gas"].append(process_row(rid,1,"floating_catalyst_CVD",reactor_type="tubular quartz CVD furnace",temperature_setpoint_C="860",holding_time_min="30" if code=="FECO" else "not_reported",carbon_source=solvent,carbon_source_flow_original="syringe-pump rate not reported",reducing_gas="H2",reducing_gas_flow_original="3000 sccm",reducing_gas_flow_sccm="3000",inert_gas="Ar",inert_gas_flow_original="2000 sccm",inert_gas_flow_sccm="2000",total_flow_original="5000 sccm plus liquid precursor",total_flow_sccm="5000"))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="metal-filled CNT identity",yield_original=out,yield_definition_original="TEM/HRTEM/Raman identity; no mass yield.",secondary_result_summary=out,CNT_type_reported="metal-filled carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary=out,CNT_type_evidence="TEM/HRTEM and Raman",outer_diameter_range_nm="dozens",morphology="ferromagnetic alloy/Fe nanowire filling inside thin-walled CNT",Raman_ratio_type="ID/IG",Raman_ratio_value=ratio,characterization_methods="TEM; HRTEM; Raman; ICP-MS; plant exposure"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Laboratory tubular CVD batch.",cost_driver_summary="Ferrocene/metallocene, chlorinated aromatic carbon source, 860 C furnace and very high Ar/H2 flow.",safety_risk="Hydrogen and chlorinated aromatic feed at 860 C; ferromagnetic nanoparticles.",emission_or_waste="Chlorinated hydrocarbon CVD exhaust and metal-filled CNT residue."));ev(t,s,sid,rid,"SPAN_0BDF4E2A8A66D13F56DE","SPAN_0BDF4E2A8A66D13F56DE","SPAN_5A43D64E2CA4F4D69316")
 return t
def build_refractory(m,s):
 sid=m["source_id"];t=base(m,"Four core pure/mixed-metal thin-film catalyst comparisons under one optimized ethylene CVD recipe.")
 recs=(("FE5","0.5 nm Fe","Fe","0.5 nm Fe","CNTs reach about 400 micrometres in 4-5 min; 80-100 micrometres/min"),("FE10","1.0 nm Fe","Fe","1.0 nm Fe","CNT growth about 15 min; ultimate length about 800 micrometres; mixed SWCNT/MWCNT with MWCNT dominance"),("FE5W5","0.5 nm Fe + 0.5 nm W","Fe; W","1:1 thickness ratio","CNTs about 950 micrometres at 30 min (~32 micrometres/min); longer lifetime; MWCNT, IG/ID ~0.66"),("FE5OS5","0.5 nm Fe + 0.5 nm Os","Fe; Os","1:1 thickness ratio","dense MWCNT mat; reduced particle coarsening/stabilization relative to pure Fe"))
 for code,label,metals,ratio,out in recs:
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,label,out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=label+" on Al2O3/SiO2/Si",active_metals=metals,support_material="15-30 nm Al2O3 on 1 micrometre SiO2/Si",metal_ratio_original=ratio,precursor_summary="Fe(acac)3; W(CO)6 or osmocene/osmium carbonyl; polystyrene in toluene",preparation_method="spin-on organometallic/polymer film then O2 RF plasma",preparation_detail="Typical 5-10 mM organometallics + 30 g/L polystyrene spun at 4000 rpm; plasma removes ligands/polymer leaving metal oxides.",reduction_condition="Ar/H2 at 750 C, 15 min",phase_or_state_summary="nanometre catalyst particles; refractory mixed metal stabilizes Fe"))
  t["reactor_process_gas"].append(process_row(rid,1,"thermal_CVD",reactor_type="1-inch-ID, 24-inch quartz-tube furnace",temperature_setpoint_C="750",holding_time_min="2-60; key comparison up to 30",pressure_original="1 atm",pressure_kPa="101.325",carbon_source="C2H4",carbon_source_flow_original="25 sccm",carbon_source_flow_sccm="25",reducing_gas="H2",reducing_gas_flow_original="25 sccm",reducing_gas_flow_sccm="25",inert_gas="Ar",inert_gas_flow_original="100 sccm",inert_gas_flow_sccm="100",total_flow_original="150 sccm",total_flow_sccm="150",gas_composition_summary="15 min Ar/H2 anneal then ethylene added"))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT mat growth lifetime/ultimate length",yield_original=out,yield_definition_original="SEM length-versus-time; no mass yield.",secondary_result_summary=out,CNT_type_reported="carbon nanotubes",CNT_type_confirmed="MWCNT-dominant",product_mixture_summary="dense vertically aligned CNT mat",CNT_type_evidence="SEM/TEM/Raman/EDS",length_summary=out,morphology="dense aligned CNT mat",alignment_or_array="vertically aligned",Raman_ratio_type="IG/ID",Raman_ratio_value="~0.66" if code=="FE5W5" else "1-2 near top for Fe10" if code=="FE10" else "not_reported",characterization_methods="SEM; TEM; micro-Raman; AFM; EDS"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Laboratory multi-coupon CVD; up to 12 catalyst compositions per run.",cost_driver_summary="Al2O3 barrier, spin-on Fe/refractory organometallics, plasma, 750 C ethylene/H2 CVD.",safety_risk="Ethylene/hydrogen at 750 C; toxic/valuable Os or W organometallics and toluene.",emission_or_waste="CVD exhaust, organometallic/polymer waste and refractory-metal CNT substrates."));ev(t,s,sid,rid,"SPAN_08259FBDAAB6CC05CF66","SPAN_2544EFE7A69217AB221F","SPAN_0740389C22B1A6F1AC30" if code=="FE5W5" else "SPAN_0230087EB9A41D76F890")
 return t
BUILDERS:dict[str,Callable]={"LIT_7DB638A390C20E74":build_retina,"LIT_85779E66B8B0D55E":build_sensor,"LIT_87B8240D8CDFE77C":build_feedstocks,"LIT_9181CCCE7A19C985":build_filled,"LIT_91BE111AC6247FA8":build_refractory}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"] for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_017_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
