#!/usr/bin/env python3
"""Transcribe the sixteenth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,issue_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=24;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID;PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_E2B9EA84E3DC4B68","LIT_E41C8A74DB04211B","LIT_E7868486310B8B49","LIT_E88F2527485B87CB","LIT_E94644A1EE5E65F3")
def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Material.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PROD","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale.",confidence="medium",value_status="review_assessment")
def build_mismatch(m,s):
 sid=m["source_id"];t=base(m,"Registered CNT title is paired with a parsed single-nanowire spectrometer paper; mismatch represented explicitly.");rid=f"{sid}_MISMATCH";r=run_row(sid,"MISMATCH","source/full-text mismatch","No CNT catalyst-support experiment exists in the parsed text","low");r["data_type"]="source_mismatch_review";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="not_applicable",active_metals="not_reported",support_material="CdSxSe1-x nanowire device in mismatched paper",preparation_method="source_mismatch"));t["reactor_process_gas"].append(process_row(rid,1,"source_mismatch",reactor_type="not_applicable",process_note="Parsed document is Science single-nanowire spectrometers."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="extractability",yield_original="no CNT synthesis data",yield_definition_original="source-integrity finding",secondary_result_summary="correct CNT paper required",CNT_type_reported="not_applicable",CNT_type_confirmed="not_applicable",product_mixture_summary="not_applicable",CNT_type_evidence="title/full-text mismatch",characterization_methods="metadata comparison"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="not assessable",cost_driver_summary="not assessable",safety_risk="not assessable",emission_or_waste="not assessable"));ev(t,s,sid,rid,"SPAN_2D55C5471C18293D6BCB","SPAN_2D55C5471C18293D6BCB","SPAN_2D55C5471C18293D6BCB");t["review_issue_log"].append(issue_row(f"{sid}_ISSUE",sid,rid,"source_integrity","source_run",rid,"data_type","Parsed full text is unrelated to registered CNT title; no experiment fabricated.",f"EVD_{rid}_PROC","high"));return t
def build_network(m,s):
 sid=m["source_id"];t=base(m,"Three secondary-Ni preparation routes on one common primary VACNT array, followed by common ethanol-CVD cross-link growth.")
 for code,method,prep,out in (("SPUT","Ni sputtering","magnetically sputter Ni onto primary VACNT","sparse secondary CNT network"),("TRANSFER","Ni foil transfer","transfer Ni foil to VACNT top then H2 anneal to particles","secondary CNT network less dense than impregnation"),("IMP","chemical impregnation","impregnate with 0.01 M Ni(NO3)2·6H2O in acetone then H2 anneal","densest 3D CNT network; in-plane conductivity 5.40 ± 0.92 W/mK")):
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,method,out));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="20 nm Ni primary catalyst plus secondary "+method,active_metals="Ni",support_material="primary VACNT array on Ti/TiN/quartz heater",metal_ratio_original="primary Ni 20 nm",precursor_summary=prep,preparation_method=method,preparation_detail=prep));t["reactor_process_gas"].append(process_row(rid,1,"primary_PECVD_plus_secondary_ethanol_CVD",reactor_type="Aixtron Blackmagic PECVD then thermal ethanol furnace",temperature_setpoint_C="750 primary; 700 secondary",holding_time_min="30 primary; 10 secondary",pressure_original="5 mbar primary",pressure_kPa="0.5",carbon_source="C2H2 primary; ethanol secondary",carbon_source_flow_original="C2H2 50 sccm primary",carbon_source_flow_sccm="50",cofeed_or_reactive_gas="NH3 250 sccm; RF 700 V, 90 W",process_note="Primary: 5 min NH3 anneal then 30 min growth. Secondary: ethanol bubbler, 700 C, 10 min."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="3D CNT network density/thermal conductivity",yield_original=out,yield_definition_original="SEM network comparison and thermal model; no mass yield",secondary_result_summary=out,CNT_type_reported="primary VACNT plus secondary CNT",CNT_type_confirmed="3D CNT network",product_mixture_summary="cross-linked secondary CNTs on primary VACNT",CNT_type_evidence="SEM/TEM",morphology="3D cross-linked network",alignment_or_array="vertical primary array with lateral secondary links",characterization_methods="SEM; TEM; IR thermal imaging; 3D heat model",application_property_summary=out));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="15 x 20 mm quartz heater sample.",cost_driver_summary="Ti/TiN heater, Ni, PECVD, secondary catalyst preparation and second 700 C CVD.",safety_risk="NH3/acetylene plasma, hydrogen anneal, ethanol vapor and Ni salts.",emission_or_waste="PECVD/CVD exhaust and Ni-containing substrates/solutions."));ev(t,s,sid,rid,"SPAN_03403EBA830E768BFBE3","SPAN_795B85DFA2F18FB9177C","SPAN_795B85DFA2F18FB9177C")
 return t
def build_chirality_review(m,s):
 sid=m["source_id"];t=base(m,"Review/modeling paper on CNT chirality and solar-cell applications; no author CNT growth run.");rid=f"{sid}_REVIEW";r=run_row(sid,"REVIEW","chirality engineering review/modeling","Reviews arc, laser and CVD recipes and models optical/solar-cell response","medium");r["data_type"]="literature_review";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="reviewed Fe/Co/Ni catalyst systems",active_metals="Fe; Co; Ni",support_material="various",preparation_method="literature_review"));t["reactor_process_gas"].append(process_row(rid,1,"literature_review_and_modeling",reactor_type="reviewed CVD/arc/laser systems",temperature_setpoint_C="multiple literature conditions",carbon_source="multiple literature feedstocks",process_note="No unique author growth experiment."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="review/model conclusion",yield_original="CVD described as producing >98% pure CNT in general statement",yield_definition_original="review claim, not author measurement",secondary_result_summary="chirality-dependent optical properties modeled for solar-cell use",CNT_type_reported="SWCNT and MWCNT",CNT_type_confirmed="review_only",product_mixture_summary="not_applicable",CNT_type_evidence="literature/modeling",characterization_methods="literature review and optical/electronic modeling",application_property_summary="solar-cell photon-density improvement modeling"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Review/model application context.",cost_driver_summary="CVD system, catalyst, purification and device integration.",safety_risk="Route-dependent high temperature/gases and CNT exposure.",emission_or_waste="Route-dependent exhaust and purification waste."));ev(t,s,sid,rid,"SPAN_127A5718F5E5964A48C7","SPAN_127A5718F5E5964A48C7","SPAN_127A5718F5E5964A48C7");t["review_issue_log"].append(issue_row(f"{sid}_ISSUE",sid,rid,"source_scope","source_run",rid,"data_type","Review/modeling article; not an author CNT synthesis run.",f"EVD_{rid}_CAT","high"));return t
def build_device_review(m,s):
 sid=m["source_id"];t=base(m,"One author-described aligned-SWCNT PECVD example embedded in a broader growth/device review.");rid=f"{sid}_PECVD";r=run_row(sid,"PECVD","patterned Co-Mo PECVD on ST-cut quartz","well-aligned SWCNTs at patterned catalyst sites");r["data_type"]="experimental_demonstration_in_review";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="patterned Co-Mo catalyst",active_metals="Co; Mo",support_material="ST-cut quartz calcined in air 900 C 24 h",metal_ratio_original="reported molar ratio 10:10:1 including catalyst components; exact third component ambiguous in parse",preparation_method="electron-beam lithography patterning",preparation_detail="~2 nm catalyst nanoparticle sites"));t["reactor_process_gas"].append(process_row(rid,1,"PECVD",reactor_type="plasma-enhanced CVD",temperature_setpoint_C="800",pressure_original="0.35 Torr",pressure_kPa="0.0467",carbon_source="source reaction gases listed in figure/text but parsed flow details incomplete",process_note="Applied electric field/plasma aligns SWCNTs on crystalline quartz."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="aligned SWCNT placement",yield_original="well-aligned SWCNTs from patterned catalyst",yield_definition_original="microscopy/device demonstration; no mass yield",secondary_result_summary="review connects placement-controlled growth to CNT FET/tunnel-transistor fabrication",CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary="aligned SWCNTs",CNT_type_evidence="AFM/SEM/device electrical behavior",outer_diameter_mean_nm="~2 catalyst particle scale; tube diameter not separately stated",alignment_or_array="field- and quartz-aligned",characterization_methods="AFM; SEM; device electrical testing",application_property_summary="integrated SWCNT transistor/tunnel-FET process context"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Patterned device-wafer demonstration.",cost_driver_summary="24 h quartz calcination, EBL catalyst patterning, PECVD and transistor fabrication.",safety_risk="Plasma/high temperature and catalyst/CNT handling.",emission_or_waste="PECVD exhaust and microfabrication waste."));ev(t,s,sid,rid,"SPAN_8CE8BD0663000807B9AE","SPAN_8CE8BD0663000807B9AE","SPAN_8CE8BD0663000807B9AE");return t
def build_chiral(m,s):
 sid=m["source_id"];t=base(m,"Three CO-CVD temperatures on epitaxial Co-MgO nanoparticles, preserving reported yield and chirality shifts.")
 for temp,yld,out in ((400,"not_reported","low-temperature SWCNT; chirality shifts toward (7,6), with selective growth at 400 C"),(500,"2.0","high (6,5) selectivity; 57 individual SWCNTs indexed in ED map"),(600,"2.8","SWCNT growth with narrow diameter distribution; higher carbon yield")):
  rid=f"{sid}_T{temp}";t["source_run"].append(run_row(sid,f"T{temp}",f"Co-MgO CO-CVD {temp} C",out));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="epitaxial fcc Co nanoparticles from CoxMg1-xO",active_metals="Co",support_material="porous MgO solid solution",precursor_summary="1.4 g Co(NO3)2·6H2O in 100 mL water mixed with 4.0 g MgO",preparation_method="aqueous impregnation, dry 90 C overnight, calcine 1000 C 20 h",phase_or_state_summary="uniform epitaxial fcc Co nanoparticles lattice-mismatched to MgO"));t["reactor_process_gas"].append(process_row(rid,1,"CO_CVD",reactor_type="Linkam CCR1000 cold-wall microreactor",temperature_setpoint_C=str(temp),holding_time_min="10",pressure_original="ambient",pressure_kPa="101.325",carbon_source="CO",carbon_source_flow_original="50 cm3/min",carbon_source_flow_sccm="50",inert_gas="Ar",inert_gas_flow_original="50 cm3/min heat-up/cooling",inert_gas_flow_sccm="50",process_note="20 mg catalyst; replace Ar fully by CO for growth."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="carbon yield/chirality",yield_original=(f"{yld} wt% carbon" if yld!="not_reported" else "carbon yield not separately reported"),yield_value_standardized=yld,yield_unit_standardized="wt.% carbon per total catalyst" if yld!="not_reported" else "not_reported",yield_definition_original="percent carbon deposited per total catalyst weight",secondary_result_summary=out,CNT_type_reported="single-walled carbon nanotubes",CNT_type_confirmed="SWCNT",product_mixture_summary=out,CNT_type_evidence="TEM/electron diffraction, Raman, UV-vis-NIR and PL",characterization_methods="in-situ ETEM; ex-situ TEM/ED; SEM; Raman; UV-vis-NIR; PL",post_treatment_or_purification="3 M HCl, water rinse, 60 C overnight dry; sodium-cholate sonication/centrifugation for spectroscopy",purification_condition="3 M HCl then dispersion and 50,000g centrifugation"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="20 mg catalyst cold-wall CVD run.",cost_driver_summary="1000 C catalyst calcination, cold-wall reactor, CO and extensive chirality characterization.",safety_risk="Carbon monoxide, cobalt salts/nanoparticles, HCl and CNT dispersion.",emission_or_waste="CO exhaust and acidic Co/Mg purification waste."));ev(t,s,sid,rid,"SPAN_6910A4EC24F7F0B08818","SPAN_6910A4EC24F7F0B08818","SPAN_A81D7746F8E4CDC530A8")
 return t
BUILDERS:dict[str,Callable]={"LIT_E2B9EA84E3DC4B68":build_mismatch,"LIT_E41C8A74DB04211B":build_network,"LIT_E7868486310B8B49":build_chirality_review,"LIT_E88F2527485B87CB":build_device_review,"LIT_E94644A1EE5E65F3":build_chiral}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"]for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_024_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
