#!/usr/bin/env python3
"""Transcribe the eighth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Any, Callable
from scripts.extraction.batch_common import ROOT, TABLES, EvidenceStore, catalyst_row, cost_row, issue_row, load_metadata, master_row, process_row, run_row, yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence, publish_package
from scripts.extraction.package_io import existing_package_metric

BATCH_ID="B_CLASS_371_20260719"; BATCH_NUMBER=16; BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID
PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
SOURCE_IDS=("LIT_6E3602008C65FB95","LIT_70C62F9DC9DF53B4","LIT_726BE13C316642AE","LIT_77436375794AF074","LIT_77ACB59A07172EE0")

def base(meta:dict[str,Any],scope:str):
    t={n:[] for n in TABLES}; m=master_row(meta,scope); m["local_file_path"]=f"data/interim/parsed_text/by_source/{meta['source_id']}.parsed.json"; m["notes"]=f"Source-specific transcription for {BATCH_NAME}."; t["source_master"].append(m); return t

def ev(t,st,sid,rid,a,b,c,review=False):
    vs="review_assessment" if review else "reported"
    add_evidence(t,st,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Catalyst/material basis.",value_status=vs)
    add_evidence(t,st,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process condition.",value_status=vs)
    add_evidence(t,st,sid,rid,"PRODUCT","yield_quality",f"{rid}_PROD","record_level",c,"Product/result.",value_status=vs)
    add_evidence(t,st,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale context.",confidence="medium",value_status="review_assessment")

def build_autonomous(meta,st):
    sid=meta["source_id"]; t=base(meta,"Two complete autonomous CNT-growth campaigns summarized by Fe-film thickness; all 135 individual points remain represented by their source dataset/figures, not invented as exact rows.")
    for code,thick,n,seed,planned,gain,outcome in (("FE0P3","0.3","50","25","25","2","planned maximum yield twice the maximum seed yield"),("FE1P0","1.0","85","32","53","3","greater absolute yield/lifetime; planned maximum yield three times the maximum seed yield")):
        rid=f"{sid}_{code}"; r=run_row(sid,code,f"ARES autonomous campaign: {thick} nm Fe",f"{n} experiments ({seed} seed, {planned} jump-regression planned); {outcome}.","medium"); r["data_type"]="experimental_campaign_summary"; t["source_run"].append(r)
        t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"{thick} nm sputtered Fe / 10 nm ALD Al2O3",active_metals="Fe",support_material="10 nm Al2O3 on etched Si/SiO2 10 micrometre pillars",metal_ratio_original=f"{thick} nm Fe film",preparation_method="ALD support and sputtered Fe thin film; air oxidation",activation_condition="no separate reduction/heat treatment; in-situ ethylene reduction during growth"))
        t["reactor_process_gas"].append(process_row(rid,1,"autonomous_cold_wall_CVD_campaign",reactor_type="ARES cold-wall laser-heated supported-catalyst microreactor with in-situ Raman",temperature_setpoint_C="campaign variable; exact point matrix in figures/dataset",holding_time_min="minutes per experiment",pressure_original="10 Torr",pressure_kPa="1.333",carbon_source="C2H4",carbon_source_flow_original="varied via partial pressure",cofeed_or_reactive_gas="0.1%, 1% or 10% CO2 premixed in Ar; latent H2O 0.8-2.5 ppm",gas_composition_summary="temperature and log partial-pressure ratio of C2H4 to CO2/H2O are campaign inputs"))
        t["yield_quality"].append(yield_row(rid,primary_yield_metric="in-situ/post-growth Raman G-band proxy yield",yield_original=outcome,yield_definition_original="Post-growth G-band area 1525-1650 cm-1 after noise subtraction, normalized by Si 520.5 cm-1; relative proxy, not mass yield.",secondary_result_summary="Best growth occurs near the jump boundary; poorer growth on both less- and more-reducing sides.",CNT_type_reported="carbon nanotubes",CNT_type_confirmed="CNT; diameters calculated where RBM observed",product_mixture_summary="CNT on supported catalyst pillars",CNT_type_evidence="in-situ/post-growth Raman and SEM",Raman_ratio_type="normalized G-band integral; weighted RBM mean",characterization_methods="in-situ Raman 532 nm; post-growth Raman; SEM"))
        t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary=f"Autonomous microreactor campaign of {n} experiments.",cost_driver_summary="ALD/sputtered micro-pillars, laser heating, controlled low-pressure gases, Raman automation and planning computation.",safety_risk="Ethylene/CO2 gas mixtures under laser heating.",emission_or_waste="Small-volume CVD exhaust and patterned catalyst chips."))
        ev(t,st,sid,rid,"SPAN_0F2F4EA3C8ADF934172E","SPAN_0F2F4EA3C8ADF934172E","SPAN_324FD290DF2C61C2346A")
        t["review_issue_log"].append(issue_row(f"{rid}_ISSUE_MATRIX",sid,rid,"series_aggregation","source_run",rid,"run_summary","Campaign points are graph/dataset-resolved; this source-level extraction preserves the explicit campaign design and stated maxima without fabricating point coordinates.",f"EVD_{rid}_PRODUCT","medium"))
    return t

def build_tailgas(meta,st):
    sid=meta["source_id"]; t=base(meta,"Front-furnace baseline and rear-furnace reclaimed-tail-gas CNT-fibre production runs.")
    recs=(("FCNT","front furnace fresh ferrocene FCCVD","2.4 wt.% ferrocene in ethanol/0.6 wt.% thiophene","8-10 mL/min","4 wt.% fibre/carbon-source yield; DWNT fibre; strength 1.27 GPa; conductivity 5.3e5 S/m"),("RCNT","rear furnace activated tail-gas Fe","deactivated 20-30 nm Fe particles carried in front-furnace tail gas; no fresh catalyst","6-8 mL/min ethanol/thiophene plus 2-3 mL/min water","0.9 wt.% fibre/carbon-source yield; about 20 cm finite fibre; mainly DWNT; 1.6 GPa; 4.7e3 S/m"))
    for code,label,cat,feed,out in recs:
        rid=f"{sid}_{code}"; t["source_run"].append(run_row(sid,code,label,out))
        t["catalyst_system"].append(catalyst_row(rid,catalyst_label=cat,active_metals="Fe",support_material="floating catalyst/no solid support",precursor_summary=cat,preparation_method="fresh ferrocene injection" if code=="FCNT" else "recovery and H2/H2O activation of tail-gas Fe particles",activation_condition="1170 C reactor; hydrogen/water remove encapsulating amorphous carbon"))
        t["reactor_process_gas"].append(process_row(rid,1,"floating_catalyst_CVD_fibre",reactor_type="double vertical-furnace spinning system" if code=="RCNT" else "front vertical FCCVD spinning furnace",temperature_setpoint_C="1170",holding_time_min="continuous/not_reported",carbon_source="ethanol",carbon_source_flow_original=feed,reducing_gas="H2",reducing_gas_flow_original="1000 sccm front; rear receives 700-800 sccm tail gas dominated by 78.60 mol% H2",inert_gas="Ar",inert_gas_flow_original="200 sccm during ramp",cofeed_or_reactive_gas="thiophene promoter; water in rear run",gas_composition_summary="rear tail gas: 12.78% CH4, 8.53% CO, 0.08% CO2, 78.60% H2" if code=="RCNT" else "ethanol + 2.4 wt.% ferrocene + 0.6 wt.% thiophene under H2"))
        t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT-fibre mass/carbon-source ratio",yield_original=out,yield_definition_original="Fibre mass divided by liquid carbon-source input.",yield_value_standardized="0.9" if code=="RCNT" else "4",yield_unit_standardized="wt.% fibre/carbon source",secondary_result_summary=out,CNT_type_reported="double-walled carbon nanotube fibre",CNT_type_confirmed="DWNT with isolated SWCNT",product_mixture_summary="aligned CNT bundles/yarn",CNT_type_evidence="SEM/TEM/Raman",outer_diameter_range_nm="bundle 20-50; isolated SWCNT about 3",length_summary="rear fibre about 20 cm",morphology="aligned bundles along yarn axis",characterization_methods="optical microscopy; SEM; TEM; Raman 532 nm; tensile; conductivity"))
        t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Continuous spinning concept; rear run reuses 700-800 sccm FCCVD tail gas.",cost_driver_summary="1170 C double furnaces, high H2 flow and liquid ethanol/thiophene injection.",safety_risk="Hot hydrogen-rich tail gas, CO/CH4, ethanol/thiophene and nanoparticle aerosol.",emission_or_waste="Tail-gas reuse reduces catalyst loss but remaining hydrogen/CO/CH4/CNT aerosol requires control."))
        ev(t,st,sid,rid,"SPAN_3E18A65CE0A9E3F48BAC","SPAN_3E18A65CE0A9E3F48BAC","SPAN_3E4061199774922DE607")
    return t

def build_membrane(meta,st):
    sid=meta["source_id"]; t=base(meta,"CNT/polymer membrane fabrication and CNT/SiNx comparison membrane; both use pre-grown VACNT mats whose detailed growth recipes are outside this source.")
    for code,label,matrix,thick,diam,out in (("CNT_POLY","VACNT/poly(styrene-block-butadiene)/polystyrene membrane","in-situ polymerized styrene + PS-b-PB","15-50 micrometres","3.3","flexible aligned CNT/polymer membrane with open CNT ends"),("CNT_SIN","VACNT/SiNx comparison membrane","low-pressure CVD SiNx","5 micrometres","1.6","rigid comparison CNT/SiNx membrane with open CNT ends")):
        rid=f"{sid}_{code}"; r=run_row(sid,code,label,out,"medium"); r["data_type"]="experimental_post_processing"; r["target_track"]="CNT_membrane_fabrication"; t["source_run"].append(r)
        t["catalyst_system"].append(catalyst_row(rid,catalyst_label="pre-grown Fe/Mo-catalysed VACNT mat",active_metals="Fe; Mo",support_material="Si wafer then "+matrix,precursor_summary="ethylene CVD VACNT from source-referenced growth method",preparation_method="VACNT growth details not fully reported here; membrane infiltration/etching is source experiment",phase_or_state_summary=f"aligned CNT embedded in {matrix}"))
        t["reactor_process_gas"].append(process_row(rid,1,"CNT_membrane_fabrication",reactor_type="sealed glass/PTFE mold and Ar-purged oven" if code=="CNT_POLY" else "low-pressure SiNx CVD plus ion milling/RIE",temperature_setpoint_C="80" if code=="CNT_POLY" else "not_reported",holding_time_min="600 polymerization" if code=="CNT_POLY" else "not_reported",carbon_source="pre-grown VACNT mat",cofeed_or_reactive_gas="0.5 wt.% AIBN; styrene/PS-b-PB" if code=="CNT_POLY" else "SiNx precursor gases not reported",process_note="PVA-supported styrene infiltration, 80 C/10 h polymerization, warm-water PVA removal, 10 vol.% HF release and CF4/O2 4:1 RIE at 10 W" if code=="CNT_POLY" else "SiNx fills gaps; Ar ion milling and oxygen-containing RIE expose/open CNT ends"))
        t["yield_quality"].append(yield_row(rid,primary_yield_metric="aligned open-pore CNT membrane",yield_original=out,yield_definition_original="Membrane morphology/transport outcome; no CNT mass yield.",secondary_result_summary=f"VACNT mat {thick}; average inner diameter {diam} nm.",CNT_type_reported="vertically aligned carbon nanotubes",CNT_type_confirmed="VACNT",product_mixture_summary=f"CNT/{matrix} composite",CNT_type_evidence="Raman/TEM and gas/liquid permeation",inner_diameter_mean_nm=diam,length_summary=thick,morphology="aligned open-ended CNT channels",characterization_methods="Raman; HRTEM; gas permeance; liquid rejection; indentation"))
        t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Laboratory membrane coupon.",cost_driver_summary="Pre-grown VACNT, polymer/SiNx infiltration, HF release and plasma end opening.",safety_risk="HF, CF4/O2 plasma, styrene/AIBN or SiNx deposition chemistry.",emission_or_waste="Fluoride/plasma exhaust, polymer/solvent waste and etched substrate."))
        ev(t,st,sid,rid,"SPAN_1D072A573059C960926B","SPAN_63480FDB98742FD1C6F5" if code=="CNT_POLY" else "SPAN_1D072A573059C960926B","SPAN_1D072A573059C960926B")
    t["review_issue_log"].append(issue_row(f"{sid}_ISSUE_GROWTH",sid,f"{sid}_CNT_POLY","critical_data_gap","reactor_process_gas",f"{sid}_CNT_POLY_S01","carbon_source","Detailed VACNT growth conditions are source-referenced rather than reported; membrane-fabrication conditions are retained without reconstructing the missing growth recipe.",f"EVD_{sid}_CNT_POLY_CAT","high")); return t

def build_aerogel(meta,st):
    sid=meta["source_id"]; t=base(meta,"Seven catalyst-mass/sulfur/metal-source conditions testing CNT-aerogel formation in methane FC-CVD.")
    recs=(("FE110_S","FeCx from ferrocene","thiophene present","110","no continuous aerogel at 1.1e2 mg/m3"),("FE160_S","FeCx from ferrocene","thiophene present","160","continuous CNT aerogel at 1.6e2 mg/m3; threshold boundary"),("FE_SPARK_NO_S","spark Fe nanoparticles","none","below 200","virtually no CNT without sulfur"),("FE_SPARK_S","spark Fe nanoparticles","thiophene","below 200","long entangled CNT bundles/web but no continuous aerogel because supply below threshold"),("CO_NO_S","cobaltocene","none","below 200","only a few short CNTs"),("CO200_S","cobaltocene","thiophene","about 200","complete continuous CNT aerogel; cobalt threshold >2e2 mg/m3"),("NI600_S","nickelocene","thiophene","above 600","small curled CNT clusters, no spinnable aerogel despite mass above estimated threshold"))
    for code,cat,sulfur,mass,out in recs:
        rid=f"{sid}_{code}"; t["source_run"].append(run_row(sid,code,f"{cat}; {sulfur}; {mass} mg/m3",out))
        metal="Fe" if code.startswith("FE") else "Co" if code.startswith("CO") else "Ni"
        t["catalyst_system"].append(catalyst_row(rid,catalyst_label=cat,active_metals=metal,support_material="floating aerosol/no solid support",metal_ratio_original=f"total catalyst solid mass {mass} mg/m3",precursor_summary=cat,preparation_method="Furnace-1 precursor decomposition/spark generation and aerosol classification",activation_condition="thiophene sulfur promoter" if sulfur!="none" else "no sulfur control"))
        t["reactor_process_gas"].append(process_row(rid,1,"two_furnace_floating_catalyst_CVD",reactor_type="two horizontal alumina furnaces; particle generator/classifier then aerogel reactor",temperature_setpoint_C="1290 (Furnace 2); Furnace 1 850-1250",carbon_source="CH4",carbon_source_flow_original="130 sccm",carbon_source_flow_sccm="130",reducing_gas="H2",reducing_gas_flow_original="700-1000 sccm plus precursor carrier",cofeed_or_reactive_gas="thiophene 3.4e-5 mol/min" if sulfur!="none" else "none",gas_composition_summary=f"CH4/H2 with {sulfur}; catalyst aerosol {mass} mg/m3"))
        t["yield_quality"].append(yield_row(rid,primary_yield_metric="continuous CNT-aerogel formation",yield_original=out,yield_definition_original="Observed aerogel/web/cluster outcome versus catalyst mass and sulfur.",secondary_result_summary=out,CNT_type_reported="carbon nanotubes/aerogel",CNT_type_confirmed="CNT" if "no CNT" not in out else "not_applicable",product_mixture_summary=out,CNT_type_evidence="SEM and Raman",morphology="branched entangled CNT network; bundles 6-40 nm and hundreds of micrometres when web/aerogel forms",characterization_methods="SMPS; XPS; SEM; Raman"))
        t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Continuous FC-CVD aerogel reactor with quantified aerosol mass supply.",reactor_capacity_or_throughput=f"catalyst aerosol {mass} mg/m3",scale_up_issue="critical mass >110-160 mg/m3 FeCx or >200 mg/m3 Co; Ni morphology prevents entanglement",cost_driver_summary="Two 850-1290 C furnaces, hydrogen/methane, metallocene or spark metal source, thiophene and aerosol classification.",safety_risk="Hot H2/CH4, sulfur compound, organometallic/nanoparticle aerosol.",emission_or_waste="CNT/catalyst aerosol and hydrocarbon/sulfur exhaust."))
        ev(t,st,sid,rid,"SPAN_30C86A9E7C5A7AAE0E3A","SPAN_30C86A9E7C5A7AAE0E3A","SPAN_8139DF35EB4F1EBEC335" if code.startswith("FE1") else "SPAN_582781E99FD799ACBD28")
    return t

def build_supports(meta,st):
    sid=meta["source_id"]; t=base(meta,"Eight matched Co/Fe support-location CCVD conditions at 1000 K; author-generated qualitative MWNT outcomes.")
    recs=(("CO_SIL","Co/silica","Co","silica","5","497","6.0","numerous well-graphitized MWNT"),("FE_Y","Fe/NaY","Fe","NaY","5","608","0.7","well-graphitized MWNT; formation proven by 1 min"),("CO_Y","Co/NaY","Co","NaY","5","632","0.7","well-graphitized MWNT"),("CO_MCM_IMP","Co/MCM-41 impregnation","Co","MCM-41","2.5","978","3.4","numerous well-graphitized MWNT"),("CO_MCM_EX","Co-MCM-41 ion exchange","Co","MCM-41","0.29","1169","3.3","only tiny indication of MWNT formation"),("CO_MCM_ISO","Co-MCM-41 isomorphous substitution","Co","MCM-41","0.01","1077","3.8","no nanotube detected"),("CO_AL","Co/alumina","Co","alumina","5","<10","not_reported","well-graphitized MWNT"),("FE_AL","Fe/alumina in-situ XPS","Fe","alumina","5","<10","not_reported","carbon/catalyst-state experiment; source does not give a standalone quantitative MWNT yield"))
    for code,label,metal,support,wt,area,pore,out in recs:
        rid=f"{sid}_{code}"; t["source_run"].append(run_row(sid,code,label,out,"medium"))
        method="ion exchange" if "exchange" in label or support=="NaY" else "isomorphous substitution" if "isomorphous" in label else "impregnation/adsorption-precipitation"
        t["catalyst_system"].append(catalyst_row(rid,catalyst_label=label,active_metals=metal,support_material=support,metal_ratio_original=f"{wt} wt.% {metal}",precursor_summary=f"{metal} acetate",preparation_method=method,preparation_detail="aqueous/solvent loading, evaporation or filtration/washing; dried at 400 K overnight",BET_surface_area_m2_g=area,pore_diameter_nm=pore))
        t["reactor_process_gas"].append(process_row(rid,1,"fixed_bed_CCVD",reactor_type="silica boat in horizontal fixed-bed flow reactor",temperature_setpoint_C="726.85 (1000 K nominal; studied 900-1100 K)",holding_time_min="1-60",carbon_source="C2H2",carbon_source_flow_original="10% of 300 mL/min",carbon_source_flow_sccm="30",inert_gas="N2",inert_gas_flow_original="90% of 300 mL/min",inert_gas_flow_sccm="270",total_flow_original="300 mL/min",total_flow_sccm="300",gas_composition_summary="10% acetylene/90% nitrogen after N2 purge and 999 K pretreatment"))
        t["yield_quality"].append(yield_row(rid,primary_yield_metric="MWNT presence/quality",yield_original=out,yield_definition_original="TEM/HRTEM qualitative outcome; total carbon weight was measured but values are not tabulated in parsed text.",secondary_result_summary=out,CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT" if "no nanotube" not in out and "tiny" not in out else "trace_MWCNT" if "tiny" in out else "not_applicable",product_mixture_summary="raw carbon plus catalyst",CNT_type_evidence="TEM/HRTEM",morphology="bent/curved, well-graphitized tubes for active external-surface catalysts",characterization_methods="gravimetry; TEM; HRTEM; XPS; XRF; XRD; BET"))
        t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Laboratory fixed-bed catalyst comparison.",cost_driver_summary="Porous supports, Co/Fe loading, 1000 K furnace, acetylene/nitrogen and HF/NaOH purification.",safety_risk="Acetylene at high temperature; HF or caustic purification; metal salts.",emission_or_waste="Carbon/catalyst solids and acidic/basic support-removal waste."))
        ev(t,st,sid,rid,"SPAN_074F7311EE0F394468D5","SPAN_06DD675524D5F8BEA86C","SPAN_074F7311EE0F394468D5")
    t["review_issue_log"].append(issue_row(f"{sid}_ISSUE_YIELD",sid,f"{sid}_CO_SIL","critical_data_gap","yield_quality",f"{sid}_CO_SIL_PROD","yield_original","The article states carbon weight gain was measured but the parsed source does not expose numeric per-catalyst values; only source-stated CNT outcomes are entered.",f"EVD_{sid}_CO_SIL_PRODUCT","medium")); return t

BUILDERS:dict[str,Callable]={"LIT_6E3602008C65FB95":build_autonomous,"LIT_70C62F9DC9DF53B4":build_tailgas,"LIT_726BE13C316642AE":build_membrane,"LIT_77436375794AF074":build_aerogel,"LIT_77ACB59A07172EE0":build_supports}
def main():
    md=load_metadata("B"); st=EvidenceStore(); ms=[]
    try:
        for sid in SOURCE_IDS:
            metric=existing_package_metric(sid,"B")
            if metric is None: ms.append(publish_package(sid,BUILDERS[sid](md[sid],st)))
            else: ms.append(metric)
    finally: st.close()
    result={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"] for x in ms),"status":"completed_needs_review"}; (REPORT_ROOT/"manual_batch_016_metrics.json").write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print(json.dumps(result,ensure_ascii=False,indent=2))
if __name__=="__main__": main()
