#!/usr/bin/env python3
"""Transcribe the twelfth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,issue_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=20;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID;PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_A7F841B38540268D","LIT_ACDBD9EA5B44494A","LIT_B3A4C977965467B8","LIT_B49F1E2FC9A56304","LIT_BA82E7DC697790E9")
def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Material.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PROD","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale.",confidence="medium",value_status="review_assessment")
def build_review(m,s):
 sid=m["source_id"];t=base(m,"Review-level overview of CNT synthesis, properties and applications; no author experiment reconstructed.");rid=f"{sid}_REVIEW";r=run_row(sid,"REVIEW","CNT synthesis overview","CVD generally 650-900 C with review-stated yield about 30%; compares arc, laser, CVD and PECVD","medium");r["data_type"]="literature_review";t["source_run"].append(r)
 t["catalyst_system"].append(catalyst_row(rid,catalyst_label="reviewed transition-metal catalysts",active_metals="Fe; Co; Ni and others",support_material="various substrates/supports",precursor_summary="Review-level catalyst families",preparation_method="literature_review"));t["reactor_process_gas"].append(process_row(rid,1,"literature_review",reactor_type="CVD/PECVD/arc/laser systems",temperature_setpoint_C="CVD typically 650-900",carbon_source="acetylene, methane and other hydrocarbons",process_note="No unique author recipe."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="review synthesis comparison",yield_original="CVD review estimate ~30% yield",yield_definition_original="Review-level generalization, not an author experimental measurement",secondary_result_summary="CVD described as lower-temperature, high-purity and scalable relative to arc/laser routes",CNT_type_reported="SWCNT and MWCNT",CNT_type_confirmed="review_only",product_mixture_summary="not_applicable",CNT_type_evidence="literature review",characterization_methods="literature review"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Review identifies CVD as large-scale-favored and arc as comparatively expensive.",cost_driver_summary="Furnace/plasma energy, catalyst, feed gas and purification.",safety_risk="High temperature, flammable gases, plasma/arc and nanopowders.",emission_or_waste="Route-specific exhaust, soot and spent catalysts."));ev(t,s,sid,rid,"SPAN_194F47688FC8BC80EAFB","SPAN_194F47688FC8BC80EAFB","SPAN_194F47688FC8BC80EAFB");t["review_issue_log"].append(issue_row(f"{sid}_ISSUE",sid,rid,"source_scope","source_run",rid,"data_type","Review-only aggregate; not an author growth run.",f"EVD_{rid}_CAT","high"));return t
def build_black_si(m,s):
 sid=m["source_id"];t=base(m,"Three CVD-duration conditions (5, 15, 30 min) for Fe-catalyzed CNT branches on black silicon.")
 for mins in (5,15,30):
  rid=f"{sid}_T{mins}";out=f"CNT branch density increases with {mins} min growth"+("; at 30 min absorbance gain vs bare bSi was 4.6% UV, 5.9% visible and 49.9% at 1200 nm" if mins==30 else "") ;t["source_run"].append(run_row(sid,f"T{mins}",f"bSi-CNT {mins} min",out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label="electrodeposited Fe nanoparticles on black-Si stems",active_metals="Fe",support_material="metal-assisted-etched black silicon",preparation_method="Fe electrodeposition",activation_condition="Ar/H2 200/100 sccm, 1000 C, 20 min"));t["reactor_process_gas"].append(process_row(rid,1,"methane_CVD",reactor_type="horizontal 1-inch quartz tube furnace",temperature_setpoint_C="1000",holding_time_min=str(mins),carbon_source="CH4",carbon_source_flow_original="10 sccm",carbon_source_flow_sccm="10",reducing_gas="H2",reducing_gas_flow_original="20 sccm growth; 100 sccm reduction",reducing_gas_flow_sccm="20",inert_gas="Ar",inert_gas_flow_original="200 sccm reduction; 500 sccm cooling",gas_composition_summary="CH4/H2 10/20 sccm after 20 min Ar/H2 reduction"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="CNT density/optical absorbance",yield_original=out,yield_definition_original="SEM density and spectral absorbance; no mass yield",secondary_result_summary=out,CNT_type_reported="CNT random network",CNT_type_confirmed="CNT",product_mixture_summary="CNT-branched black-Si hybrid",CNT_type_evidence="SEM/Raman",morphology="random CNT network branching from black-Si stems",characterization_methods="SEM; Raman; UV-vis-NIR absorbance",application_property_summary=out));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Black-Si coupon optical absorber.",cost_driver_summary="HF/AgNO3 black-Si etch, Fe electrodeposition and 1000 C methane CVD.",safety_risk="HF, methane/hydrogen at 1000 C and nanostructured Si/CNT handling.",emission_or_waste="HF/Ag metal etchant waste and CVD exhaust."));ev(t,s,sid,rid,"SPAN_1597F4273B2B6023B8D0","SPAN_1597F4273B2B6023B8D0","SPAN_0A5C6CA3F3A007C288F0")
 return t
def build_sensor(m,s):
 sid=m["source_id"];t=base(m,"One linked post-processing chain from purchased MWCNT through acid functionalization, CBS nanoparticle incorporation and molecularly imprinted electrode.");rid=f"{sid}_SENSOR";r=run_row(sid,"SENSOR","CBSNP/f-MWCNT hydrazine-imprinted electrode","Hydrazine linear range to 1e-8 M and LOD 3e-10 M");r["data_type"]="experimental_post_processing";r["target_track"]="CNT_sensor_material";t["source_run"].append(r)
 t["catalyst_system"].append(catalyst_row(rid,catalyst_label="Co-Ba-stannate nanoparticles on carboxylated MWCNT",active_metals="Co; Ba; Sn",support_material="purchased MWCNT and glassy-carbon electrode",precursor_summary="Ba nitrate, Co nitrate, sodium stannate; >=99% MWCNT, 1-2 micrometre length",preparation_method="acid functionalization, co-precipitation/800 C calcination, sonication and drop-casting",preparation_detail="0.4 g MWCNT in 10 mL HNO3:H2SO4 3:1 at 100 C 20 h; CBS precursors 2 mg each, NaOH, dry/calcine 800 C 6 h; 20 microlitre of 1 mg/mL dispersion on GCE"));t["reactor_process_gas"].append(process_row(rid,1,"CNT_sensor_postprocessing",reactor_type="acid flask, furnace and electrochemical cell",temperature_setpoint_C="100 functionalization; 800 CBS heat treatment",holding_time_min="1200 acid stir; 360 heat treatment",carbon_source="pre-existing MWCNT",process_note="Electropolymerize 100 mM pyrrole + 25 mM hydrazine for 20 CV cycles; desorb in 1 M NaCl 20 min."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="hydrazine sensor performance",yield_original="LOD 3.0e-10 M; upper linear range 1.0e-8 M",yield_definition_original="Electroanalytical outcome, not CNT synthesis yield",secondary_result_summary="Selective hydrazine-imprinted CBSNP/f-MWCNT/GCE applied to tap water",CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT input",product_mixture_summary="CBSNP/f-MWCNT molecularly imprinted electrode",CNT_type_evidence="supplier plus SEM/TEM/Raman/XPS/XRD",length_summary="1-2 micrometres",characterization_methods="FTIR; SEM; TEM; XPS; XRD; Raman; CV; EIS; SWV",application_property_summary="Hydrazine LOD 3e-10 M"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Sub-gram nanocomposite and 20 microlitre electrode coating.",cost_driver_summary="Purchased MWCNT, concentrated acids, 800 C nanoparticle calcination and electrochemical imprinting.",safety_risk="Strong mixed acids, hydrazine, cobalt/barium/tin salts and nanopowders.",emission_or_waste="Acid/metal/hydrazine liquids and electrode waste."));ev(t,s,sid,rid,"SPAN_5D6FFBBF5076FEDEC953","SPAN_2A0B8D19DAC759FDDD42","SPAN_2A0B8D19DAC759FDDD42");return t
def build_graphene(m,s):
 sid=m["source_id"];t=base(m,"Two catalyst-free methane-CVD graphene coating campaigns using SWCNT paper and aligned MWCNT sheet substrates.")
 for code,substrate,ch4,time,out in (("SWCNT","arc-derived SWCNT paper","5","1-10","1-3 graphene layers locally after 3 min; thicker/conical coatings at longer times"),("MWCNT","10-20 micrometre aligned sheet cleaved from 6 mm MWCNT forest","10","1-120","uniform concentric thickening; coating thickness increases nearly constantly with time")):
  rid=f"{sid}_{code}";r=run_row(sid,code,f"graphene on {code}",out);r["data_type"]="experimental_post_processing";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="catalyst-free CNT basal-plane substrate",active_metals="none",support_material=substrate,preparation_method="CNT substrate preparation then catalyst-free methane CVD",phase_or_state_summary="new graphene layers self-assemble as seamless coaxial cylinders"));t["reactor_process_gas"].append(process_row(rid,1,"catalyst_free_graphene_CVD",reactor_type="horizontal tube furnace",temperature_setpoint_C="1150",holding_time_min=time,pressure_original="150 Torr",pressure_kPa="20",carbon_source="CH4",carbon_source_flow_original=f"{ch4} sccm",carbon_source_flow_sccm=ch4,inert_gas="Ar",inert_gas_flow_original="150 sccm",inert_gas_flow_sccm="150",total_flow_original=f"{150+int(ch4)} sccm",total_flow_sccm=str(150+int(ch4))));t["yield_quality"].append(yield_row(rid,primary_yield_metric="graphene coating formation",yield_original=out,yield_definition_original="TEM-observed layer/thickness evolution; no mass yield",secondary_result_summary=out,CNT_type_reported=code, CNT_type_confirmed=code,product_mixture_summary="pre-existing CNT with conformal graphene shells",CNT_type_evidence="HRTEM and Raman",morphology="seamless coaxial graphene coating",characterization_methods="TEM/HRTEM; SEM; Raman"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="CNT paper/sheet coupon post-processing.",cost_driver_summary="1150 C furnace, methane/argon and long deposition for MWCNT coatings.",safety_risk="Methane at 1150 C and CNT sheet/soot handling.",emission_or_waste="Methane CVD exhaust and carbon-coated CNT scraps."));ev(t,s,sid,rid,"SPAN_528873B2FDB36FD09232","SPAN_528873B2FDB36FD09232","SPAN_14D6B4DD00F41F3790EA")
 return t
def build_decoration(m,s):
 sid=m["source_id"];t=base(m,"All nine fluidized-bed CVD decoration runs in Table 1 (SnO2, Si and Fe; raw or gas-pretreated MWCNTs).")
 recs=(("T02","raw","SnO2","500","90","SnCl4/H2O","27","78"),("T05","raw","SnO2","550","125","SnCl4/H2O","17","90"),("T06","H2O","SnO2","550","120","SnCl4/H2O","15","79"),("S30","raw","Si","500","60","SiH4","40","100"),("W6","H2O","Si","500","60","SiH4","38.6","100"),("NCNT3","raw","Fe","650","180","ferrocene","57","87"),("NCNT9","O3","Fe","650","180","ferrocene","52.5","100"),("NCNT10","O3","Fe","550","180","ferrocene","37.8","90"),("NCNT13","raw","Fe","650","180","ferrocene","40","84"))
 for code,pre,dep,temp,time,feed,mass,conv in recs:
  rid=f"{sid}_{code}";out=f"{mass} g deposited; precursor conversion {conv}%";r=run_row(sid,code,f"{dep} decoration {code}",out);r["data_type"]="experimental_post_processing";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"{dep} nanoparticles on {pre}-pretreated MWCNT",active_metals="Sn" if dep=="SnO2" else dep, support_material="100 g Graphistrength C100 MWCNT balls",precursor_summary=feed,preparation_method="fluidized-bed CVD decoration",preparation_detail=("H2O vapor 650 C 60 min before deposition" if pre=="H2O" else "ozone pretreatment" if pre=="O3" else "raw MWCNT without purification"),phase_or_state_summary=dep+" nanoparticles"));t["reactor_process_gas"].append(process_row(rid,1,"fluidized_bed_CVD_decoration",reactor_type="8.3 cm ID, 1 m vertical stainless-steel two-zone FBCVD reactor",temperature_setpoint_C=temp,holding_time_min=time,pressure_original="atmospheric",pressure_kPa="101.325",carbon_source="pre-existing MWCNT",cofeed_or_reactive_gas=feed,inert_gas="N2",process_note="100 g MWCNT bed; HEPA-filtered exhaust. Pretreatment as specified."));morph="~20 nm Si nanoparticles" if dep=="Si" else "50-500 nm Fe/Fe3C particles with graphenic shells" if dep=="Fe" else "SnO2 nanoparticles; water pretreatment increases nucleation";t["yield_quality"].append(yield_row(rid,primary_yield_metric="nanoparticle deposition mass/conversion",yield_original=out,yield_value_standardized=mass,yield_unit_standardized="g deposited material",yield_definition_original="bed weighing and precursor conversion",secondary_result_summary=morph,CNT_type_reported="multi-walled carbon nanotube substrate",CNT_type_confirmed="MWCNT input",product_mixture_summary=f"{dep}-decorated MWCNT balls",CNT_type_evidence="supplier plus TEM/SEM",outer_diameter_mean_nm="12",wall_number_summary="10-25",morphology=morph,characterization_methods="SEM/EDX; HRTEM; XRD; ICP-MS; bed weighing"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="100 g MWCNT fluidized-bed decoration batch.",cost_driver_summary=f"Large heated fluidized bed, N2, {feed}, pretreatment and HEPA filtration.",safety_risk="Pyrophoric silane" if dep=="Si" else "Corrosive SnCl4/H2O chemistry and HCl byproduct" if dep=="SnO2" else "Ferrocene aerosol and hot nanopowder bed",emission_or_waste="HEPA-captured fines and precursor/byproduct exhaust."));ev(t,s,sid,rid,"SPAN_1EAF15D25FA49595F7F6","SPAN_CA8CA42DF563F18D3E93","SPAN_0485BEA52E60EBFC02A6" if dep=="Si" else "SPAN_CA8CA42DF563F18D3E93")
 return t
BUILDERS:dict[str,Callable]={"LIT_A7F841B38540268D":build_review,"LIT_ACDBD9EA5B44494A":build_black_si,"LIT_B3A4C977965467B8":build_sensor,"LIT_B49F1E2FC9A56304":build_graphene,"LIT_BA82E7DC697790E9":build_decoration}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"]for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_020_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
