#!/usr/bin/env python3
"""Transcribe the fifteenth five-paper B-class batch."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,issue_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric
BATCH_ID="B_CLASS_371_20260719";BATCH_NUMBER=23;BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}";BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID;PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
SOURCE_IDS=("LIT_D74C5ABB8CDC64C5","LIT_D861CF4FAB1F2A48","LIT_DD8F9900B35A354B","LIT_E030672E9652A069","LIT_E047BBA44C22AA22")
def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c,review=False):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Material.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PROD","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale.",confidence="medium",value_status="review_assessment")
def build_serpentine(m,s):
 sid=m["source_id"];t=base(m,"One high-yield serpentine-CNT quartz growth recipe using molecular Fe-Mo Müller catalyst.");rid=f"{sid}_MULLER";t["source_run"].append(run_row(sid,"MULLER","Müller Fe-Mo cluster catalyst on quartz","long high-yield serpentine CNTs with >50 continuous turns; catalyst-derived diameter centered near 1 nm"));t["catalyst_system"].append(catalyst_row(rid,catalyst_label="Fe-Mo Müller molecular cluster on quartz",active_metals="Fe; Mo",support_material="ST-cut quartz",precursor_summary="dilute Müller cluster catalyst in ethanol, approximately 1e-7 to 1e-8",preparation_method="wet deposition/spreading",preparation_detail="quartz annealed about 900 C for ~8 h; catalyst spread, oxidized 500 C 1 h",reduction_condition="Ar/H2 300/100 sccm at 750 C for 1 h"));t["reactor_process_gas"].append(process_row(rid,1,"ethanol_CVD",reactor_type="quartz-tube CVD",temperature_setpoint_C="880",carbon_source="ethanol vapor",reducing_gas="H2",reducing_gas_flow_original="10 sccm through ethanol bubbler",reducing_gas_flow_sccm="10",inert_gas="Ar",inert_gas_flow_original="20 sccm through ethanol bubbler",inert_gas_flow_sccm="20",total_flow_original="30 sccm through ethanol bubbler",total_flow_sccm="30"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="serpentine CNT morphology/yield",yield_original="high-yield long serpentines; >50 turns observed",yield_definition_original="SEM/AFM morphology; no mass yield",secondary_result_summary="serpentine turns follow gas-flow direction; catalyst makes narrow diameter distribution centered ~1 nm",CNT_type_reported="serpentine carbon nanotubes",CNT_type_confirmed="SWCNT/few-wall",product_mixture_summary="long isolated serpentine tubes",CNT_type_evidence="AFM height/diameter and electrical measurements",outer_diameter_mean_nm="~1",outer_diameter_range_nm="mostly <2",morphology="serpentine with many continuous turns",alignment_or_array="flow-directed serpentine paths",characterization_methods="SEM; AFM; electrical transport"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Quartz coupon CVD with very low catalyst concentration and low growth-gas flow.",cost_driver_summary="Long quartz anneal, molecular Fe-Mo catalyst and 880 C ethanol CVD.",safety_risk="Hydrogen/ethanol at 880 C and nanomaterial handling.",emission_or_waste="Alcohol CVD exhaust and catalyst-coated quartz."));ev(t,s,sid,rid,"SPAN_16ABDCA5B3F9C6ADC69B","SPAN_A2F79B778CF805DF05EF","SPAN_16ABDCA5B3F9C6ADC69B");return t
def build_radio(m,s):
 sid=m["source_id"];t=base(m,"Two author-synthesized 14C-labeled CNT materials (MWCNT and SWCNT) with complete growth and purification conditions.")
 recs=(("MWCNT","Ni/MgO citrate catalyst","Ni","600","300","30","30-70","99 ± 1","0.122 ± 0.004 mCi/g"),("SWCNT","Fe/MgO catalyst","Fe","850","60 plus Ar 250","15","1-2","92 ± 0.4","1.35 ± 0.03 mCi/g"))
 for code,label,metal,temp,flow,time,diam,purity,radio in recs:
  rid=f"{sid}_{code}";out=f"{purity}% carbon; specific radioactivity {radio}";t["source_run"].append(run_row(sid,code,f"14C-{code}",out));prep="1.94 g Ni nitrate + 2.56 g Mg nitrate + 2 g citric acid in 20 mL water; dry 100 C; calcine 700 C 5 h" if code=="MWCNT" else "anneal alkaline Mg carbonate 400 C 1 h Ar; 1 g Fe nitrate/100 mL water + 10 g Mg carbonate; sonicate 30 min, dry and grind";t["catalyst_system"].append(catalyst_row(rid,catalyst_label=label,active_metals=metal,support_material="MgO/magnesium carbonate-derived support",precursor_summary=prep,preparation_method="citrate/nitrate calcination" if code=="MWCNT" else "aqueous impregnation",preparation_detail=prep,activation_condition="H2 heat-up to 600 C" if code=="MWCNT" else "Ar heat-up to 850 C"));t["reactor_process_gas"].append(process_row(rid,1,"radiolabeled_methane_CVD",reactor_type="quartz-boat tube reactor",temperature_setpoint_C=temp,holding_time_min=time,carbon_source="mixture of 14C-labeled and regular CH4",carbon_source_flow_original=f"{flow} mL/min",carbon_source_flow_sccm="300" if code=="MWCNT" else "60",inert_gas="Ar",inert_gas_flow_original="cooling Ar" if code=="MWCNT" else "250 mL/min mixed with methane and during heat/cool",process_note="100 mg catalyst" if code=="MWCNT" else "1 g catalyst"));t["yield_quality"].append(yield_row(rid,primary_yield_metric="purified carbon purity/radioactivity",yield_original=out,yield_definition_original="TGA carbon fraction and biological oxidation/scintillation specific activity",secondary_result_summary="Lengths hundreds of nm to a few micrometres; minimal amorphous carbon",CNT_type_reported=code,CNT_type_confirmed=code,product_mixture_summary=f"purified radiolabeled {code}",CNT_type_evidence="TEM, Raman and TGA",outer_diameter_range_nm=diam,length_summary="hundreds of nanometres to a few micrometres",TGA_carbon_content_wt_percent=purity.split(" ")[0],purity_basis="TGA carbon percentage",characterization_methods="TEM; Raman 785 nm; TGA; biological oxidation/scintillation",post_treatment_or_purification="10 M HCl bath sonication 1 h",purification_condition="10 M HCl, 1 h sonication"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="100 mg catalyst MWCNT batch or 1 g catalyst SWCNT batch for environmental tracer study.",cost_driver_summary="Radioactive methane, supported catalyst, furnace and concentrated-HCl purification.",safety_risk="14C methane/radiological control, hydrogen/methane, 10 M HCl and CNT exposure.",emission_or_waste="Radioactive CVD exhaust controls and acidic Ni/Fe/Mg waste."));ev(t,s,sid,rid,"SPAN_7283D4982F1977AA3CBB","SPAN_7283D4982F1977AA3CBB","SPAN_36093D3564C33AF710A8")
 return t
def build_mismatch(m,s):
 sid=m["source_id"];t=base(m,"Parsed full text is a single-nanowire spectrometer paper and does not match the registered CNT-catalyst title; mismatch retained explicitly.");rid=f"{sid}_MISMATCH";r=run_row(sid,"MISMATCH","source/full-text mismatch","No CNT growth experiment extractable from the supplied parsed text","low");r["data_type"]="source_mismatch_review";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="not_applicable: mismatched nanowire-spectrometer source",active_metals="not_reported",support_material="not_applicable",preparation_method="source_mismatch"));t["reactor_process_gas"].append(process_row(rid,1,"source_mismatch",reactor_type="not_applicable",process_note="Parsed document identifies Science 365 (2019) single-nanowire spectrometers, not the registered CNT catalyst paper."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="extractability",yield_original="no CNT synthesis data in parsed document",yield_definition_original="source integrity finding",secondary_result_summary="Requires correct full text before catalyst-state extraction",CNT_type_reported="not_applicable",CNT_type_confirmed="not_applicable",product_mixture_summary="not_applicable",CNT_type_evidence="parsed title/content mismatch",characterization_methods="source metadata/full-text comparison"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Not assessable from mismatched source.",cost_driver_summary="Not assessable.",safety_risk="Not assessable.",emission_or_waste="Not assessable."));ev(t,s,sid,rid,"SPAN_CF00752AAA268D5FF4A2","SPAN_CF00752AAA268D5FF4A2","SPAN_CF00752AAA268D5FF4A2",review=True);t["review_issue_log"].append(issue_row(f"{sid}_ISSUE",sid,rid,"source_integrity","source_run",rid,"data_type","Parsed full text is a different paper (Single-nanowire spectrometers); no CNT run was fabricated.",f"EVD_{rid}_PROC","high"));return t
def build_app_review(m,s):
 sid=m["source_id"];t=base(m,"Review of CNT technical applications, synthesis, purification and toxicity; no author growth experiment.");rid=f"{sid}_REVIEW";r=run_row(sid,"REVIEW","technical applications review","CVD described as simple/economic and commercially relevant; synthesis/purification challenges surveyed","medium");r["data_type"]="literature_review";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label="reviewed metal-catalyst CVD systems",active_metals="transition metals, not uniquely specified",support_material="various",preparation_method="literature_review"));t["reactor_process_gas"].append(process_row(rid,1,"literature_review",reactor_type="CVD and other synthesis routes",carbon_source="various hydrocarbons",process_note="No author experiment; review spans microelectronics, storage, filtration, biomedical and energy applications."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="review conclusion",yield_original="CVD favored for commercial production; purification/yield/defect tradeoffs remain",yield_definition_original="qualitative review",secondary_result_summary="Applications and property tables summarized without a unique CNT synthesis run",CNT_type_reported="SWCNT and MWCNT",CNT_type_confirmed="review_only",product_mixture_summary="not_applicable",CNT_type_evidence="literature review",characterization_methods="literature review"));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Review-level commercial application context.",cost_driver_summary="Synthesis energy, catalyst, purification, dispersion and integration.",safety_risk="CNT toxicity/dispersion and route-dependent process hazards.",emission_or_waste="Spent catalysts, purification liquids and nanomaterial release."));ev(t,s,sid,rid,"SPAN_1BA7D145B314B7281BEC","SPAN_B9F6D701AB357C8B0456","SPAN_80C30121978F060F244D",review=True);t["review_issue_log"].append(issue_row(f"{sid}_ISSUE",sid,rid,"source_scope","source_run",rid,"data_type","Review-only row; not an author synthesis run.",f"EVD_{rid}_CAT","high"));return t
def build_nipt(m,s):
 sid=m["source_id"];t=base(m,"Two prepared Ni-Pt/MWCNT catalyst formulations with linked acid functionalization, impregnation/calcination and NO2 removal results.")
 for code,ni,pt,out in (("NI15PT5","15 wt% Ni","5 wt% Pt","70% removal at 150 C; up to ~91% at 300 C under reported profiles"),("NI25PT3","25 wt% Ni","3 wt% Pt","92% removal at 300 C in headline condition; up to 98% in space-velocity test")):
  rid=f"{sid}_{code}";r=run_row(sid,code,f"{ni}-{pt}/MWCNT",out);r["data_type"]="experimental_post_processing";r["target_track"]="CNT_supported_catalyst";t["source_run"].append(r);t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"{ni}-{pt}/acid-functionalized MWCNT",active_metals="Ni; Pt",support_material="CVD-produced MWCNT",metal_ratio_original=f"nominal {ni}, {pt}",preparation_method="sequential wet impregnation and calcination",preparation_detail="MWCNT acid treated with 70% HNO3 at 120 C 4 h plus second acid stage; Ni solution mixed at 80 C and dried; Pt precursor added/heated; calcine 400 C 3 h"));t["reactor_process_gas"].append(process_row(rid,1,"NO2_catalytic_reactor_test",reactor_type="fixed catalyst-bed flow reactor",temperature_setpoint_C="100-300",carbon_source="pre-existing MWCNT support",cofeed_or_reactive_gas="NO2/H2O-containing test gas",total_flow_original="2 or 2.6 L/min; space velocity 20000 or 25000 h-1",process_note="NO2 concentration 3000-5000 ppm; catalyst first reduced by mixed gas temperature program."));t["yield_quality"].append(yield_row(rid,primary_yield_metric="NO2 removal efficiency",yield_original=out,yield_definition_original="reactor inlet/outlet NO2 removal efficiency; not CNT growth yield",secondary_result_summary=out,CNT_type_reported="multi-walled carbon nanotube support",CNT_type_confirmed="MWCNT input",product_mixture_summary="Ni-Pt nanoparticles supported on functionalized MWCNT",CNT_type_evidence="SEM/EDS/XRD/FTIR/TPR",characterization_methods="XRD; SEM/EDS; FTIR; H2-TPR; flow-reactor gas analysis",application_property_summary=out));t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Laboratory fixed-bed NO2-removal catalyst.",cost_driver_summary="MWCNT acid treatment, Ni/Pt loading, 400 C calcination and Pt content.",safety_risk="Concentrated nitric acid, platinum/nickel salts, NO2 and hot reduction gas.",emission_or_waste="Acidic Ni/Pt liquids, NOx exhaust and spent CNT catalyst."));ev(t,s,sid,rid,"SPAN_0EE5268237E9CC76D136","SPAN_0EE5268237E9CC76D136","SPAN_0675859F7C0AE627EE98")
 return t
BUILDERS:dict[str,Callable]={"LIT_D74C5ABB8CDC64C5":build_serpentine,"LIT_D861CF4FAB1F2A48":build_radio,"LIT_DD8F9900B35A354B":build_mismatch,"LIT_E030672E9652A069":build_app_review,"LIT_E047BBA44C22AA22":build_nipt}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 r={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"]for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_023_metrics.json").write_text(json.dumps(r,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
