#!/usr/bin/env python3
"""Transcribe the eleventh five-paper B-class batch into complete eight-table packages."""
from __future__ import annotations
import json
from typing import Callable
from scripts.extraction.batch_common import ROOT,TABLES,EvidenceStore,catalyst_row,cost_row,load_metadata,master_row,process_row,run_row,yield_row
from scripts.extraction.build_b_class_batch_001 import add_evidence,publish_package
from scripts.extraction.package_io import existing_package_metric

BATCH_ID="B_CLASS_371_20260719"; BATCH_NUMBER=19; BATCH_NAME=f"{BATCH_ID}_MANUAL_{BATCH_NUMBER:03d}"
REPORT_ROOT = ROOT / "runs/extraction/B/batches" / BATCH_ID
REPORT_ROOT.mkdir(parents=True, exist_ok=True)
BATCH_ROOT=ROOT/"runs/extraction/B/batches"/BATCH_ID; PACKAGE_ROOT=ROOT/"data/interim/extraction/B"
SOURCE_IDS=("LIT_9D1D16C5D2C154FD","LIT_A2AD11A61964181A","LIT_A51E66EB3D1E73F8","LIT_A5F937C1E53DFE57","LIT_A72F77DDF27B1E9C")

def base(m,scope):
 t={n:[] for n in TABLES};x=master_row(m,scope);x["local_file_path"]=f"data/interim/parsed_text/by_source/{m['source_id']}.parsed.json";x["notes"]=f"Source-specific transcription for {BATCH_NAME}.";t["source_master"].append(x);return t
def ev(t,s,sid,rid,a,b,c):
 add_evidence(t,s,sid,rid,"CAT","catalyst_system",f"{rid}_CAT","record_level",a,"Catalyst/material.");add_evidence(t,s,sid,rid,"PROC","reactor_process_gas",f"{rid}_S01","record_level",b,"Process.");add_evidence(t,s,sid,rid,"PRODUCT","yield_quality",f"{rid}_PROD","record_level",c,"Outcome.");add_evidence(t,s,sid,rid,"SCALE","cost_scale_review",rid,"record_level",b,"Scale context.",confidence="medium",value_status="review_assessment")

def build_moce(m,s):
 sid=m["source_id"];t=base(m,"Nine MgO-supported Fe/Mo/Ce catalyst compositions from Tables 1-2, each retained as a distinct CVD run.")
 recs=(("FE100",100,0,0,"10.9","0.09","Yes","212"),("MO100",0,100,0,"12.2","0.78","No","not_reported"),("CE100",0,0,100,"10.3","0.92","No","not_reported"),("CE10",90,0,10,"14.2","0.10","Yes","188"),("CE50",50,0,50,"13.6","0.20","Yes","188"),("CE90",10,0,90,"13.6","0.81","Yes","188"),("MO10",90,10,0,"18.8","0.11","Yes","212"),("MO50",50,50,0,"30.3","0.17","Yes","212"),("MO90",10,90,0,"15.9","0.40","Yes","212"))
 for code,fe,mo,ce,mg,dg,rbm,peak in recs:
  rid=f"{sid}_{code}";metals="; ".join(x for x,v in (("Fe",fe),("Mo",mo),("Ce",ce)) if v);out=f"{mg} mg graphitic carbon; D/G {dg}; RBM {rbm}";t["source_run"].append(run_row(sid,code,f"Fe/Mo/Ce {fe}/{mo}/{ce} on MgO",out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"{code} on MgO",active_metals=metals,support_material="MgO nanopowder",metal_ratio_original=f"Fe/Mo/Ce={fe}/{mo}/{ce}; total metal 28 mol% vs MgO",precursor_summary="Fe(NO3)3·9H2O; (NH4)2MoO4; Ce(NO3)3·6H2O as applicable",preparation_method="incipient-water slurry impregnation",preparation_detail="grind salts with MgO; minimal DI water; stir 20 min; ultrasonicate 10 min; dry 80 C overnight"))
  t["reactor_process_gas"].append(process_row(rid,1,"methane_CVD",reactor_type="25.4 mm alumina work tube furnace",temperature_setpoint_C="900",holding_time_min="30",carbon_source="CH4",carbon_source_flow_original="200 cm3/min",carbon_source_flow_sccm="200",inert_gas="Ar",inert_gas_flow_original="400 cm3/min heat-up/cool-down",inert_gas_flow_sccm="400",process_note="0.1 g catalyst; heat at 30 C/min under Ar; switch to methane at 900 C."))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="graphitic carbon mass",yield_original=f"{mg} mg",yield_value_standardized=mg,yield_unit_standardized="mg graphitic carbon per 0.1 g catalyst batch",yield_definition_original="TGA high-temperature carbon burn-off; microscopy/RBM indicate close approximation to CNT mass",secondary_result_summary=out,CNT_type_reported="SWCNT" if rbm=="Yes" else "graphitic carbon with no clear SWCNT RBM",CNT_type_confirmed="SWCNT" if rbm=="Yes" else "not_confirmed",product_mixture_summary=out,CNT_type_evidence="TEM/SEM plus Raman RBM",RBM_peak_reported=peak,Raman_ratio_type="ID/IG",Raman_ratio_value=dg,characterization_methods="TEM; SEM; Raman; TGA"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="0.1 g catalyst laboratory tube-CVD batch.",cost_driver_summary="MgO and nitrate/molybdate salts, 900 C furnace, methane and argon.",safety_risk="Methane at 900 C; Fe/Mo/Ce salts and CNT powder.",emission_or_waste="Methane CVD exhaust and acid-soluble MgO/metal catalyst residue."));ev(t,s,sid,rid,"SPAN_0B1B6BB849C79BC86523","SPAN_D61A043B2380678F8640","SPAN_0B1B6BB849C79BC86523")
 return t

def build_emitters(m,s):
 sid=m["source_id"];t=base(m,"Four explicitly tabulated VACNT bundle-array geometries A-D with field-emission outcomes.")
 recs=(("A","square","30","2","2.0","1020","1.0e5"),("B","square","45","3","2.8","840","4.9e4"),("C","hexagonal","30","2","1.6","1770","1.6e5"),("D","hexagonal","45","3","2.5","905","7.0e4"))
 for code,arr,pitch,ratio,turnon,beta,density in recs:
  rid=f"{sid}_{code}";out=f"turn-on field {turnon} V/micrometre; enhancement factor {beta}; bundle density {density} cm-2";t["source_run"].append(run_row(sid,code,f"{arr} bundle array, {pitch} micrometre pitch",out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label="3 nm Fe / 5 nm Al patterned catalyst",active_metals="Fe",support_material="5 nm Al buffer on 10 x 10 mm Si",metal_ratio_original="3 nm Fe over 5 nm Al",preparation_method="photolithography plus electron-beam evaporation",preparation_detail=f"10 micrometre circular catalyst patterns in {arr} arrangement at {pitch} micrometre pitch"))
  t["reactor_process_gas"].append(process_row(rid,1,"thermal_CVD",reactor_type="thermal CVD",temperature_setpoint_C="750",pressure_original="4 Torr",pressure_kPa="0.533",carbon_source="C2H2",holding_time_min="adjusted to obtain 15 micrometre bundle height; exact time not reported"))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="field-emission performance",yield_original=out,yield_definition_original="Turn-on field/enhancement factor from J-E measurement; not mass yield",secondary_result_summary=f"15 micrometre high, 10 micrometre diameter cylindrical VACNT bundles; L/H={ratio}",CNT_type_reported="vertically aligned carbon nanotube bundles",CNT_type_confirmed="VACNT bundle",product_mixture_summary="patterned VACNT bundle emitter array",CNT_type_evidence="SEM",length_summary="15 micrometres",morphology="10 micrometre cylindrical bundles",alignment_or_array=f"{arr} array, {pitch} micrometre pitch",characterization_methods="SEM; field-emission J-E and stability; fluorescent screen",application_property_summary=out))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="10 x 10 mm patterned emitter sample.",cost_driver_summary="Photolithography, e-beam Al/Fe deposition, 750 C low-pressure acetylene CVD and vacuum field-emission test.",safety_risk="Acetylene at 750 C; high voltage/high vacuum and CNT emitter exposure.",emission_or_waste="CVD exhaust and lithography/metal-coated Si waste."));ev(t,s,sid,rid,"SPAN_B05E7E9B5DC8C0863B90","SPAN_B05E7E9B5DC8C0863B90","SPAN_DD36536E961186B124AE")
 return t

def build_purification(m,s):
 sid=m["source_id"];t=base(m,"Four Co:Mo:MgO catalyst preparation/loading combinations with linked methane-CVD and HCl purification outcomes.")
 recs=(("IMP_5_10","impregnation","5:10:85","88","8.1"),("SG_5_10","sol-gel","5:10:85","85","9.0"),("IMP_5_20","impregnation","5:20:75","68","not_reported"),("SG_5_20","sol-gel","5:20:75","81","not_reported"))
 for code,method,ratio,yld,diam in recs:
  rid=f"{sid}_{code}";out=f"carbon yield {yld}%; MWNT diameter 3-20 nm";t["source_run"].append(run_row(sid,code,f"CoMo/MgO {ratio} by {method}",out))
  prep="MgO impregnated with Co nitrate/ammonium molybdate; dry 120 C; calcine 550 C 2 h" if method=="impregnation" else "Co/Mo/Mg nitrate plus 10 g citric acid; stir 90 C 1 h; dry 120 C; calcine 550 C"
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=f"CoMo/MgO {ratio} {method}",active_metals="Co; Mo",support_material="MgO",metal_ratio_original=f"Co:Mo:MgO={ratio} by weight",precursor_summary="Co(NO3)2·6H2O; (NH4)6Mo7O24·4H2O; MgO or Mg(NO3)2·6H2O",preparation_method=method,preparation_detail=prep,activation_condition="H2 150 mL/min to 500 C"))
  t["reactor_process_gas"].append(process_row(rid,1,"fluidized_bed_methane_CVD",reactor_type="vertical fluidized-bed reactor",temperature_setpoint_C="800",holding_time_min="30",carbon_source="CH4",carbon_source_flow_original="150 mL/min",carbon_source_flow_sccm="150",reducing_gas="H2",reducing_gas_flow_original="150 mL/min to 500 C",reducing_gas_flow_sccm="150",inert_gas="N2",inert_gas_flow_original="150 mL/min during 500-800 C ramp and cooling",inert_gas_flow_sccm="150",process_note="1 g catalyst; 10 C/min ramp. Purification: 0.4 g CNT in 100 mL 0.3 M HCl, agitate 2 h, sonicate 30 min, agitate 2 h, age 8 h, filter/wash, dry 120 C 12 h."))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="carbon yield",yield_original=f"{yld}%",yield_value_standardized=yld,yield_unit_standardized="wt.% carbon",yield_definition_original="TGA-derived carbon yield of as-produced product",secondary_result_summary=out,CNT_type_reported="multi-walled carbon nanotubes",CNT_type_confirmed="MWCNT",product_mixture_summary="low-amorphous-carbon MWNT plus MgO/Co/Mo catalyst before purification",CNT_type_evidence="TEM and single 550-590 C TPO oxidation peak",outer_diameter_mean_nm=diam,outer_diameter_range_nm="3-20",morphology="well-structured MWNT; more bamboo-like defects at 20 wt% Mo",characterization_methods="SEM; TEM; EDX; XRD; XPS; Raman; TGA/TPO",post_treatment_or_purification="mild HCl purification",purification_condition="0.3 M HCl sequence; complete MgO removal but partial Co/Mo residue"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="1 g catalyst fluidized-bed batch; 0.4 g aliquot purification.",cost_driver_summary="Catalyst preparation, 800 C fluidized bed, methane/H2/N2 and multi-hour dilute-HCl purification.",safety_risk="Hydrogen/methane at 800 C, HCl and Co/Mo/CNT powders.",emission_or_waste="CVD exhaust and acidic Mg/Co/Mo-containing purification liquor."));ev(t,s,sid,rid,"SPAN_618F8E0243C639874DE1","SPAN_618F8E0243C639874DE1","SPAN_1421583CCFFEE8B9E352")
 return t

def build_continuous(m,s):
 sid=m["source_id"];t=base(m,"Two Fe-aerosol cooling experiments and one sequential Fe-to-Co aerosol experiment resolving continuous catalyst feeding.")
 recs=(("FE_STD","2.5 wt% ferrocene/toluene, standard ~2 h furnace cooling","850","15","~925 micrometre VACNT carpet; Fe ~3.7 wt% at top and ~1.5 wt% through much of carpet"),("FE_QUENCH","2.5 wt% ferrocene/toluene, rapid furnace-movement quench","850","15","~790 micrometre VACNT carpet; numerous external nanoparticles; Fe ~6.5 wt% at top and 2-2.5 wt% through carpet"),("FE_CO_SEQ","ferrocene followed by cobaltocene sequential aerosol","800","not_reported","bilayer aligned VACNT carpet: 100 micrometre top + 15 micrometre bottom; Fe/Co mixed catalyst segments"))
 for code,prec,temp,time,out in recs:
  rid=f"{sid}_{code}";t["source_run"].append(run_row(sid,code,prec,out))
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label=prec,active_metals="Fe" if code!="FE_CO_SEQ" else "Fe; Co",support_material="quartz reactor substrate/base-growth surface",precursor_summary=prec,preparation_method="aerosolized metallocene/toluene continuous feed",preparation_detail="solution nebulized and carried in Ar through a 200 C evaporator",phase_or_state_summary="gas-phase-nucleated nanoparticles continuously feed root catalyst particles"))
  t["reactor_process_gas"].append(process_row(rid,1,"aerosol_assisted_CCVD",reactor_type="45 cm tubular furnace with quartz reactor at atmospheric pressure",temperature_setpoint_C=temp,holding_time_min=time,pressure_original="atmospheric",pressure_kPa="101.325",carbon_source="toluene",cofeed_or_reactive_gas="ferrocene aerosol" if code!="FE_CO_SEQ" else "ferrocene aerosol followed by cobaltocene aerosol",inert_gas="Ar",process_note="No enhancer; aerosol evaporator 200 C. "+("Rapid quench after synthesis." if code=="FE_QUENCH" else "Standard furnace-inertia cooling." if code=="FE_STD" else "Sequential precursor switch.")))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="VACNT carpet structure/metal profile",yield_original=out,yield_definition_original="SEM/WDS/TEM-EELS outcome; no mass yield",secondary_result_summary=out,CNT_type_reported="vertically aligned carbon nanotubes",CNT_type_confirmed="VACNT",product_mixture_summary=out,CNT_type_evidence="SEM; TEM/STEM-EELS; WDS; Raman",length_summary="~925 micrometres" if code=="FE_STD" else "~790 micrometres" if code=="FE_QUENCH" else "115 micrometres total",morphology="aligned carpet" if code!="FE_CO_SEQ" else "two aligned layers with disordered top region",alignment_or_array="vertically aligned carpet",characterization_methods="SEM; TEM; STEM-EELS; WDS; Raman"))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="15 min laboratory aerosol-CCVD carpet for Fe cooling comparison; sequential study at laboratory furnace scale.",cost_driver_summary="Metallocene/toluene aerosol, argon, 800-850 C furnace and electron microscopy/elemental profiling.",safety_risk="Toluene/metallocene aerosol at high temperature; air-sensitive cobaltocene and CNT aerosol.",emission_or_waste="Organic/metal aerosol exhaust and metal-containing VACNT material."));ev(t,s,sid,rid,"SPAN_37F24C9FD7D970F5D9DD","SPAN_37F24C9FD7D970F5D9DD","SPAN_0BD131B00F66D2F810EC" if code=="FE_CO_SEQ" else "SPAN_37F24C9FD7D970F5D9DD")
 return t

def build_thesis(m,s):
 sid=m["source_id"];t=base(m,"Four thesis experiments/series: ethanol trial, productive methanol/hexane base recipe, water-addition series and Gd-salt trial.")
 recs=(("ETHANOL","ethanol/ferrocene/thiophene","1150","ethanol; ferrocene 0.5-2 g/100 mL; thiophene 0.3 g/100 mL","No large CNT assembly; black amorphous-carbon coating with some CNT fibers","SPAN_2D968186C8020368AA71"),("BASE","90 vol% methanol + 10 vol% n-hexane; 0.5% thiophene; 0.5-2% ferrocene","1200","base spinnable recipe","large quantity of CNT films/cylindrical sock; typical fuel 0.8 mL/min and Ar 500-2500 sccm","SPAN_677EC9E4EA5D5589098F"),("WATER","base recipe + 1-5 vol% water","1200","water concentration series","1-4 vol% water generated thinner/more transparent CNT cylinder; 5% failed","SPAN_517E65A5AEF0964665DE"),("GD","base recipe + GdCl3·6H2O","1200","0.4-0.5 ferrocene; 0.3 thiophene; final condition included Gd additive","thin/continuous sock at final 200 sccm Ar condition; material felt more resilient","SPAN_352E51A80DFDF4B2C343"))
 for code,label,temp,feed,out,span in recs:
  rid=f"{sid}_{code}";r=run_row(sid,code,label,out,"medium" if code in ("WATER","GD") else "high");r["data_type"]="experimental_series_summary" if code in ("WATER","GD") else "experimental_run";t["source_run"].append(r)
  t["catalyst_system"].append(catalyst_row(rid,catalyst_label="ferrocene floating Fe catalyst"+(" with GdCl3·6H2O" if code=="GD" else ""),active_metals="Fe; Gd" if code=="GD" else "Fe",support_material="floating/no solid support",precursor_summary=feed,preparation_method="liquid injection floating-catalyst CVD",preparation_detail="ferrocene carbon/catalyst provider; thiophene sulfur promoter"))
  t["reactor_process_gas"].append(process_row(rid,1,"floating_catalyst_CVD",reactor_type="multi-field quartz/alumina-tube reactor",temperature_setpoint_C=temp,carbon_source="ethanol" if code=="ETHANOL" else "methanol/n-hexane 9:1",carbon_source_flow_original="0.8 mL/min typical" if code!="ETHANOL" else "not_reported",inert_gas="Ar",inert_gas_flow_original="~500 sccm" if code=="ETHANOL" else "500-2500 sccm typical" if code=="BASE" else "condition series; 200 sccm in final Gd run" if code=="GD" else "not individually reported",cofeed_or_reactive_gas="thiophene promoter; "+("water 1-5 vol%" if code=="WATER" else "GdCl3·6H2O" if code=="GD" else "none beyond recipe"),process_note=feed))
  t["yield_quality"].append(yield_row(rid,primary_yield_metric="spinnable CNT assembly formation",yield_original=out,yield_definition_original="Observed sock/cylinder/fiber production; no mass yield",secondary_result_summary=out,CNT_type_reported="CNT fiber/film; base recipe intended mostly DWCNT",CNT_type_confirmed="CNT assembly" if code!="ETHANOL" else "limited CNT fibers",product_mixture_summary=out,CNT_type_evidence="visual collection plus later Raman/TEM characterization",morphology="continuous cylindrical sock/fiber" if code!="ETHANOL" else "amorphous wall coating with sparse fibers",characterization_methods="visual process observation; Raman; SEM/TEM in thesis characterization chapter",application_property_summary="water/alcohol densification and direct spinning at ~50 rpm when Ar ~1000 sccm" if code=="BASE" else out))
  t["cost_scale_review"].append(cost_row(rid,scale_evidence_summary="Continuous laboratory floating-catalyst reactor producing collectable yarn/sheet precursor where successful.",cost_driver_summary="1200 C reactor, methanol/hexane/ferrocene/thiophene feed, argon and continuous collection.",safety_risk="Flammable alcohol/hexane, thiophene, ferrocene/Gd salt and CNT aerosol at 1150-1200 C.",emission_or_waste="Organic/metal-containing reactor exhaust, amorphous carbon and CNT offcuts."));ev(t,s,sid,rid,span,span,span)
 return t

BUILDERS:dict[str,Callable]={"LIT_9D1D16C5D2C154FD":build_moce,"LIT_A2AD11A61964181A":build_emitters,"LIT_A51E66EB3D1E73F8":build_purification,"LIT_A5F937C1E53DFE57":build_continuous,"LIT_A72F77DDF27B1E9C":build_thesis}
def main():
 md=load_metadata("B");s=EvidenceStore();ms=[]
 try:
  for sid in SOURCE_IDS:
   metric=existing_package_metric(sid,"B")
   if metric is None:ms.append(publish_package(sid,BUILDERS[sid](md[sid],s)))
   else:ms.append(metric)
 finally:s.close()
 result={"batch_id":BATCH_NAME,"sources":ms,"total_runs":sum(x["row_counts"]["source_run"] for x in ms),"status":"completed_needs_review"};(REPORT_ROOT/"manual_batch_019_metrics.json").write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(result,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
